//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: vmnet.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf

// MARK: - Client protocol

public protocol Vmnet_VMNetServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol? { get }

  func getSerialization(
    _ request: Vmnet_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<Vmnet_Empty, Vmnet_SerializationReply>
}

extension Vmnet_VMNetServiceClientProtocol {
  public var serviceName: String { return "vmnet.VMNetService" }

  public func getSerialization(
    _ request: Vmnet_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Vmnet_Empty, Vmnet_SerializationReply> {
    return self.makeUnaryCall(
      path: Vmnet_VMNetServiceClientMetadata.Methods.getSerialization.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSerializationInterceptors() ?? []
    )
  }
}

// MARK: - Client interceptor factory protocol

public protocol Vmnet_VMNetServiceClientInterceptorFactoryProtocol: Sendable {
  func makeGetSerializationInterceptors() -> [ClientInterceptor<Vmnet_Empty, Vmnet_SerializationReply>]
}

// MARK: - NIO client

public struct Vmnet_VMNetServiceNIOClient: Vmnet_VMNetServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

// MARK: - Async client protocol

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Vmnet_VMNetServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol? { get }

  func makeGetSerializationCall(
    _ request: Vmnet_Empty,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Vmnet_Empty, Vmnet_SerializationReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Vmnet_VMNetServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Vmnet_VMNetServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol? { return nil }

  public func makeGetSerializationCall(
    _ request: Vmnet_Empty,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Vmnet_Empty, Vmnet_SerializationReply> {
    return self.makeAsyncUnaryCall(
      path: Vmnet_VMNetServiceClientMetadata.Methods.getSerialization.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSerializationInterceptors() ?? []
    )
  }

  public func getSerialization(
    _ request: Vmnet_Empty,
    callOptions: CallOptions? = nil
  ) async throws -> Vmnet_SerializationReply {
    return try await self.makeGetSerializationCall(request, callOptions: callOptions).response
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Vmnet_VMNetServiceAsyncClient: Vmnet_VMNetServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Vmnet_VMNetServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

// MARK: - Client metadata

public enum Vmnet_VMNetServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "VMNetService",
    fullName: "vmnet.VMNetService",
    methods: [
      Vmnet_VMNetServiceClientMetadata.Methods.getSerialization,
    ]
  )

  public enum Methods {
    public static let getSerialization = GRPCMethodDescriptor(
      name: "GetSerialization",
      path: "/vmnet.VMNetService/GetSerialization",
      type: GRPCCallType.unary
    )
  }
}

// MARK: - Server provider protocol

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Vmnet_VMNetServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Vmnet_VMNetServiceServerInterceptorFactoryProtocol? { get }

  func getSerialization(
    request: Vmnet_Empty,
    context: GRPCAsyncServerCallContext
  ) async throws -> Vmnet_SerializationReply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Vmnet_VMNetServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Vmnet_VMNetServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Vmnet_VMNetServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Vmnet_VMNetServiceServerInterceptorFactoryProtocol? { return nil }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetSerialization":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Vmnet_Empty>(),
        responseSerializer: ProtobufSerializer<Vmnet_SerializationReply>(),
        interceptors: self.interceptors?.makeGetSerializationInterceptors() ?? [],
        wrapping: { try await self.getSerialization(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

// MARK: - Server interceptor factory protocol

public protocol Vmnet_VMNetServiceServerInterceptorFactoryProtocol: Sendable {
  func makeGetSerializationInterceptors() -> [ServerInterceptor<Vmnet_Empty, Vmnet_SerializationReply>]
}

// MARK: - Server metadata

public enum Vmnet_VMNetServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "VMNetService",
    fullName: "vmnet.VMNetService",
    methods: [
      Vmnet_VMNetServiceServerMetadata.Methods.getSerialization,
    ]
  )

  public enum Methods {
    public static let getSerialization = GRPCMethodDescriptor(
      name: "GetSerialization",
      path: "/vmnet.VMNetService/GetSerialization",
      type: GRPCCallType.unary
    )
  }
}
