// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vmnet.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Vmnet_Empty: Sendable {
  public var unknownFields = SwiftProtobuf.UnknownStorage()
  public init() {}
}

public nonisolated struct Vmnet_SerializationReply: Sendable {
  public var data: Data = Data()
  public var success: Bool = false
  public var reason: String {
    get { return _reason ?? String() }
    set { _reason = newValue }
  }
  public var hasReason: Bool { return _reason != nil }
  public mutating func clearReason() { _reason = nil }

  public var unknownFields = SwiftProtobuf.UnknownStorage()
  public init() {}

  fileprivate var _reason: String? = nil
}

// MARK: - Extension: Message conformance

extension Vmnet_Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _vmnet_package + ".Empty"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func == (lhs: Vmnet_Empty, rhs: Vmnet_Empty) -> Bool {
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}

extension Vmnet_SerializationReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _vmnet_package + ".SerializationReply"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}success\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNum = try decoder.nextFieldNumber() {
      switch fieldNum {
      case 1: try decoder.decodeSingularBytesField(value: &self.data)
      case 2: try decoder.decodeSingularBoolField(value: &self.success)
      case 3: try decoder.decodeSingularStringField(value: &self._reason)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    if let v = self._reason {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func == (lhs: Vmnet_SerializationReply, rhs: Vmnet_SerializationReply) -> Bool {
    if lhs.data != rhs.data { return false }
    if lhs.success != rhs.success { return false }
    if lhs._reason != rhs._reason { return false }
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}

fileprivate let _vmnet_package = "vmnet"
