// swift-tools-version:5.10
import PackageDescription
let package = Package(
	name: "Caker",
	platforms: [
		.macOS(.v13)
	],
	products: [
		.executable(name: "caked", targets: ["caked"]),
		.executable(name: "cakectl", targets: ["cakectl"]),
		.library(name: "GRPCLib", targets: ["GRPCLib"])
	],
	dependencies: [
		.package(url: "https://github.com/amodm/iso9660-swift", branch: "main"),
		.package(url: "https://github.com/antlr/antlr4", exact: "4.13.2"),
		.package(url: "https://github.com/apple/swift-algorithms", from: "1.2.0"),
		.package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
		.package(url: "https://github.com/apple/swift-async-algorithms", branch: "main"),
		.package(url: "https://github.com/apple/swift-atomics.git", .upToNextMajor(from: "1.2.0")),
		.package(url: "https://github.com/apple/swift-certificates.git", from: "1.6.1"),
		.package(url: "https://github.com/apple/swift-collections.git", from: "1.0.5"),
		.package(url: "https://github.com/apple/swift-crypto.git", from: "3.9.1"),
		.package(url: "https://github.com/apple/swift-log.git", from: "1.6.2"),
		.package(url: "https://github.com/apple/swift-nio-extras.git", from: "1.26.0"),
		.package(url: "https://github.com/apple/swift-nio-http2.git", from: "1.36.0"),
		.package(url: "https://github.com/apple/swift-nio-ssh.git", from: "0.10.0"),
		.package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.30.0"),
		.package(url: "https://github.com/apple/swift-nio-transport-services.git", from: "1.24.0"),
		.package(url: "https://github.com/apple/swift-nio.git", from: "2.82.1"),
		.package(url: "https://github.com/apple/swift-protobuf.git", from: "1.29.0"),
		.package(url: "https://github.com/cfilipov/TextTable", branch: "master"),
		.package(url: "https://github.com/DimaRU/Shout.git", branch: "master"),
		.package(url: "https://github.com/Fred78290/cakeagent.git", revision: "abd3c6b008acba2c4f59dcd503ded2816d0e526d"),
		.package(url: "https://github.com/Fred78290/GzipSwift", branch: "main"),
		.package(url: "https://github.com/Fred78290/swift-nio-portforwarding.git", from: "0.2.7"),
		.package(url: "https://github.com/fumoboy007/swift-retry", from: "0.2.4"),
		.package(url: "https://github.com/getsentry/sentry-cocoa", from: "8.49.2"),
		.package(url: "https://github.com/groue/Semaphore", from: "0.0.8"),
		.package(url: "https://github.com/grpc/grpc-swift.git", from: "1.25.0"),
		.package(url: "https://github.com/jozefizso/swift-xattr", from: "3.0.0"),
		.package(url: "https://github.com/jpsim/Yams", from: "5.1.3"),
		.package(url: "https://github.com/malcommac/SwiftDate", from: "7.0.0"),
		.package(url: "https://github.com/mhdhejazi/Dynamic", branch: "master"),
		.package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.53.6"),
		.package(url: "https://github.com/orchetect/SwiftRadix", from: "1.3.1"),
		.package(url: "https://github.com/sersoft-gmbh/swift-sysctl.git", from: "1.8.0"),
	],
	targets: [
		.binaryTarget(name: "Qcow2convert", path: "qcow2convert/Qcow2convert.xcframework"),
		.target(name: "GRPCLib", dependencies: [
				.product(name: "ArgumentParser", package: "swift-argument-parser"),
				.product(name: "GRPC", package: "grpc-swift"),
				.product(name: "CakeAgentLib", package: "CakeAgent"),
				.product(name: "NIOPortForwarding", package: "swift-nio-portforwarding")
			],
			path: "Sources/grpc",
			exclude: [
				"generate.sh",
				"service.proto",
			]
		),
		.executableTarget(name: "caked", dependencies: [
				.product(name: "Algorithms", package: "swift-algorithms"),
				.product(name: "Antlr4Static", package: "Antlr4"),
				.product(name: "ArgumentParser", package: "swift-argument-parser"),
				.product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
				.product(name: "Atomics", package: "swift-atomics"),
				.product(name: "CakeAgentLib", package: "CakeAgent"),
				.product(name: "Crypto", package: "swift-crypto"),
				.product(name: "DMRetry", package: "swift-retry"),
				.product(name: "Dynamic", package: "Dynamic"),
				.product(name: "GRPC", package: "grpc-swift"),
				.product(name: "Gzip", package: "GzipSwift"),
				.product(name: "ISO9660", package: "iso9660-swift"),
				.product(name: "Logging", package: "swift-log"),
				.product(name: "NIOCore", package: "swift-nio"),
				.product(name: "NIOEmbedded", package: "swift-nio"),
				.product(name: "NIOExtras", package: "swift-nio-extras"),
				.product(name: "NIOFoundationCompat", package: "swift-nio"),
				.product(name: "NIOHTTP1", package: "swift-nio"),
				.product(name: "NIOHTTP2", package: "swift-nio-http2"),
				.product(name: "NIOPortForwarding", package: "swift-nio-portforwarding"),
				.product(name: "NIOPosix", package: "swift-nio"),
				.product(name: "NIOSSH", package: "swift-nio-ssh"),
				.product(name: "NIOSSL", package: "swift-nio-ssl"),
				.product(name: "NIOTLS", package: "swift-nio"),
				.product(name: "Semaphore", package: "Semaphore"),
				.product(name: "Sentry", package: "sentry-cocoa"),
				.product(name: "Shout", package: "Shout"),
				.product(name: "SwiftDate", package: "SwiftDate"),
				.product(name: "SwiftRadix", package: "SwiftRadix"),
				.product(name: "Sysctl", package: "swift-sysctl"),
				.product(name: "TextTable", package: "TextTable"),
				.product(name: "X509", package: "swift-certificates"),
				.product(name: "XAttr", package: "swift-xattr"),
				.product(name: "Yams", package: "Yams"),
				.target(name: "GRPCLib"),
				.target(name: "Qcow2convert"),
			],
			exclude: [
				"MountService/GRPC/generate.sh",
				"MountService/GRPC/mount.proto"
			]
		),
		.executableTarget(name: "cakectl", dependencies: [
				.product(name: "Algorithms", package: "swift-algorithms"),
				.product(name: "Antlr4Static", package: "Antlr4"),
				.product(name: "ArgumentParser", package: "swift-argument-parser"),
				.product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
				.product(name: "Atomics", package: "swift-atomics"),
				.product(name: "CakeAgentLib", package: "CakeAgent"),
				.product(name: "Crypto", package: "swift-crypto"),
				.product(name: "DMRetry", package: "swift-retry"),
				.product(name: "Dynamic", package: "Dynamic"),
				.product(name: "GRPC", package: "grpc-swift"),
				.product(name: "ISO9660", package: "iso9660-swift"),
				.product(name: "NIOCore", package: "swift-nio"),
				.product(name: "NIOEmbedded", package: "swift-nio"),
				.product(name: "NIOExtras", package: "swift-nio-extras"),
				.product(name: "NIOFoundationCompat", package: "swift-nio"),
				.product(name: "NIOHTTP1", package: "swift-nio"),
				.product(name: "NIOHTTP2", package: "swift-nio-http2"),
				.product(name: "NIOPortForwarding", package: "swift-nio-portforwarding"),
				.product(name: "NIOPosix", package: "swift-nio"),
				.product(name: "NIOSSL", package: "swift-nio-ssl"),
				.product(name: "NIOTLS", package: "swift-nio"),
				.product(name: "Semaphore", package: "Semaphore"),
				.product(name: "Sentry", package: "sentry-cocoa"),
				.product(name: "SwiftDate", package: "SwiftDate"),
				.product(name: "SwiftRadix", package: "SwiftRadix"),
				.product(name: "Sysctl", package: "swift-sysctl"),
				.product(name: "TextTable", package: "TextTable"),
				.product(name: "X509", package: "swift-certificates"),
				.product(name: "XAttr", package: "swift-xattr"),
				.product(name: "Yams", package: "Yams"),
				.target(name: "GRPCLib"),
			],
			exclude: [
			]
		),
		.testTarget(name: "CakerTests",
			dependencies: [
				"GRPCLib",
				"caked",
				"cakectl"
			],
			exclude: [
				"echo.py",
				"TestPlan.xctestplan"
			]
		)
	]
)
