// swift-tools-version:5.10

import PackageDescription
let package = Package(
	name: "TartHelper",
	platforms: [
		.macOS(.v13)
	],
	products: [
		.executable(name: "tarthelper", targets: ["tarthelper"]),
		.executable(name: "tartctl", targets: ["tartctl"]),
		.library(name: "GRPCLib", targets: ["GRPCLib"]),
	],
	dependencies: [
		.package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.1"),
		.package(url: "https://github.com/mhdhejazi/Dynamic", branch: "master"),
		.package(url: "https://github.com/apple/swift-algorithms", from: "1.2.0"),
		.package(url: "https://github.com/apple/swift-async-algorithms", branch: "main"),
		.package(url: "https://github.com/malcommac/SwiftDate", from: "7.0.0"),
		.package(url: "https://github.com/antlr/antlr4", exact: "4.13.2"),
		.package(url: "https://github.com/apple/swift-atomics.git", .upToNextMajor(from: "1.2.0")),
		.package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.53.6"),
		.package(url: "https://github.com/getsentry/sentry-cocoa", from: "8.36.0"),
		.package(url: "https://github.com/cfilipov/TextTable", branch: "master"),
		.package(url: "https://github.com/sersoft-gmbh/swift-sysctl.git", from: "1.8.0"),
		.package(url: "https://github.com/orchetect/SwiftRadix", from: "1.3.1"),
		.package(url: "https://github.com/groue/Semaphore", from: "0.0.8"),
		.package(url: "https://github.com/fumoboy007/swift-retry", from: "0.2.3"),
		.package(url: "https://github.com/jozefizso/swift-xattr", from: "3.0.0"),
		.package(url: "https://github.com/amodm/iso9660-swift", branch: "main"),
		.package(url: "https://github.com/jpsim/Yams", from: "5.1.3"),
		.package(url: "https://github.com/john-mueller/ShellOut", branch: "swift-5.1"),
		.package(url: "https://github.com/apple/swift-certificates.git", from: "1.6.1"),
		.package(url: "https://github.com/apple/swift-crypto.git", from: "3.9.1"),
		.package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.23.0"),
		.package(url: "https://github.com/grpc/grpc-swift.git", from: "1.24.2"),
		.package(url: "https://github.com/apple/swift-nio.git", from: "2.65.0"),
		.package(url: "https://github.com/apple/swift-nio-http2.git", from: "1.32.0"),
		.package(url: "https://github.com/apple/swift-nio-transport-services.git", from: "1.15.0"),
		.package(url: "https://github.com/apple/swift-nio-extras.git", from: "1.24.0"),
		.package(url: "https://github.com/apple/swift-collections.git", from: "1.0.5"),
		.package(url: "https://github.com/apple/swift-protobuf.git", from: "1.28.1"),
	],
	targets: [
		.binaryTarget(name: "Qcow2convert", path: "qcow2convert/Qcow2convert.xcframework"),
		.target(name: "GRPCLib", dependencies: [
			.product(name: "GRPC", package: "grpc-swift")
		],
		path: "Sources/grpc",
		exclude: [
			"generate.sh",
			"service.proto",
		]),
		.executableTarget(name: "tarthelper", dependencies: [
			.target(name: "GRPCLib"),
			.target(name: "Qcow2convert"),
			.product(name: "Algorithms", package: "swift-algorithms"),
			.product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
			.product(name: "ArgumentParser", package: "swift-argument-parser"),
			.product(name: "Dynamic", package: "Dynamic"),
			.product(name: "SwiftDate", package: "SwiftDate"),
			.product(name: "Antlr4Static", package: "Antlr4"),
			.product(name: "Atomics", package: "swift-atomics"),
			.product(name: "Sentry", package: "sentry-cocoa"),
			.product(name: "TextTable", package: "TextTable"),
			.product(name: "Sysctl", package: "swift-sysctl"),
			.product(name: "SwiftRadix", package: "SwiftRadix"),
			.product(name: "Semaphore", package: "Semaphore"),
			.product(name: "DMRetry", package: "swift-retry"),
			.product(name: "XAttr", package: "swift-xattr"),
			.product(name: "ISO9660", package: "iso9660-swift"),
			.product(name: "Yams", package: "Yams"),
			.product(name: "ShellOut", package: "ShellOut"),
			.product(name: "X509", package: "swift-certificates"),
			.product(name: "Crypto", package: "swift-crypto"),
			.product(name: "GRPC", package: "grpc-swift"),
			.product(name: "NIOCore", package: "swift-nio"),
			.product(name: "NIOEmbedded", package: "swift-nio"),
			.product(name: "NIOExtras", package: "swift-nio-extras"),
			.product(name: "NIOFoundationCompat", package: "swift-nio"),
			.product(name: "NIOHTTP1", package: "swift-nio"),
			.product(name: "NIOHTTP2", package: "swift-nio-http2"),
			.product(name: "NIOPosix", package: "swift-nio"),
			.product(name: "NIOSSL", package: "swift-nio-ssl"),
			.product(name: "NIOTLS", package: "swift-nio")
		]),
		.executableTarget(name: "tartctl", dependencies: [
			.target(name: "GRPCLib"),
			.product(name: "Algorithms", package: "swift-algorithms"),
			.product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
			.product(name: "ArgumentParser", package: "swift-argument-parser"),
			.product(name: "Dynamic", package: "Dynamic"),
			.product(name: "SwiftDate", package: "SwiftDate"),
			.product(name: "Antlr4Static", package: "Antlr4"),
			.product(name: "Atomics", package: "swift-atomics"),
			.product(name: "Sentry", package: "sentry-cocoa"),
			.product(name: "TextTable", package: "TextTable"),
			.product(name: "Sysctl", package: "swift-sysctl"),
			.product(name: "SwiftRadix", package: "SwiftRadix"),
			.product(name: "Semaphore", package: "Semaphore"),
			.product(name: "DMRetry", package: "swift-retry"),
			.product(name: "XAttr", package: "swift-xattr"),
			.product(name: "ISO9660", package: "iso9660-swift"),
			.product(name: "Yams", package: "Yams"),
			.product(name: "ShellOut", package: "ShellOut"),
			.product(name: "X509", package: "swift-certificates"),
			.product(name: "Crypto", package: "swift-crypto"),
			.product(name: "GRPC", package: "grpc-swift"),
			.product(name: "NIOCore", package: "swift-nio"),
			.product(name: "NIOEmbedded", package: "swift-nio"),
			.product(name: "NIOExtras", package: "swift-nio-extras"),
			.product(name: "NIOFoundationCompat", package: "swift-nio"),
			.product(name: "NIOHTTP1", package: "swift-nio"),
			.product(name: "NIOHTTP2", package: "swift-nio-http2"),
			.product(name: "NIOPosix", package: "swift-nio"),
			.product(name: "NIOSSL", package: "swift-nio-ssl"),
			.product(name: "NIOTLS", package: "swift-nio")
		]),
		.testTarget(name: "TartHelperTests", dependencies: ["GRPCLib", "tarthelper", "tartctl"])
	]
)
