//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: mount.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Vmrun_ServiceClient`, then call methods of this protocol to make API calls.
public protocol Vmrun_ServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? { get }

  func mount(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Vmrun_MountRequest, Vmrun_MountReply>

  func umount(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Vmrun_MountRequest, Vmrun_MountReply>
}

extension Vmrun_ServiceClientProtocol {
  public var serviceName: String {
    return "vmrun.Service"
  }

  /// Unary call to Mount
  ///
  /// - Parameters:
  ///   - request: Request to send to Mount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func mount(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Vmrun_MountRequest, Vmrun_MountReply> {
    return self.makeUnaryCall(
      path: Vmrun_ServiceClientMetadata.Methods.mount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMountInterceptors() ?? []
    )
  }

  /// Unary call to Umount
  ///
  /// - Parameters:
  ///   - request: Request to send to Umount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func umount(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Vmrun_MountRequest, Vmrun_MountReply> {
    return self.makeUnaryCall(
      path: Vmrun_ServiceClientMetadata.Methods.umount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUmountInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Vmrun_ServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Vmrun_ServiceNIOClient")
public final class Vmrun_ServiceClient: Vmrun_ServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the vmrun.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Vmrun_ServiceNIOClient: Vmrun_ServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the vmrun.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Vmrun_ServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? { get }

  func makeMountCall(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Vmrun_MountRequest, Vmrun_MountReply>

  func makeUmountCall(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Vmrun_MountRequest, Vmrun_MountReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Vmrun_ServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Vmrun_ServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeMountCall(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Vmrun_MountRequest, Vmrun_MountReply> {
    return self.makeAsyncUnaryCall(
      path: Vmrun_ServiceClientMetadata.Methods.mount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMountInterceptors() ?? []
    )
  }

  public func makeUmountCall(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Vmrun_MountRequest, Vmrun_MountReply> {
    return self.makeAsyncUnaryCall(
      path: Vmrun_ServiceClientMetadata.Methods.umount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUmountInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Vmrun_ServiceAsyncClientProtocol {
  public func mount(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Vmrun_MountReply {
    return try await self.performAsyncUnaryCall(
      path: Vmrun_ServiceClientMetadata.Methods.mount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMountInterceptors() ?? []
    )
  }

  public func umount(
    _ request: Vmrun_MountRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Vmrun_MountReply {
    return try await self.performAsyncUnaryCall(
      path: Vmrun_ServiceClientMetadata.Methods.umount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUmountInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Vmrun_ServiceAsyncClient: Vmrun_ServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Vmrun_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Vmrun_ServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'mount'.
  func makeMountInterceptors() -> [ClientInterceptor<Vmrun_MountRequest, Vmrun_MountReply>]

  /// - Returns: Interceptors to use when invoking 'umount'.
  func makeUmountInterceptors() -> [ClientInterceptor<Vmrun_MountRequest, Vmrun_MountReply>]
}

public enum Vmrun_ServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "vmrun.Service",
    methods: [
      Vmrun_ServiceClientMetadata.Methods.mount,
      Vmrun_ServiceClientMetadata.Methods.umount,
    ]
  )

  public enum Methods {
    public static let mount = GRPCMethodDescriptor(
      name: "Mount",
      path: "/vmrun.Service/Mount",
      type: GRPCCallType.unary
    )

    public static let umount = GRPCMethodDescriptor(
      name: "Umount",
      path: "/vmrun.Service/Umount",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Vmrun_ServiceProvider: CallHandlerProvider {
  var interceptors: Vmrun_ServiceServerInterceptorFactoryProtocol? { get }

  func mount(request: Vmrun_MountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Vmrun_MountReply>

  func umount(request: Vmrun_MountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Vmrun_MountReply>
}

extension Vmrun_ServiceProvider {
  public var serviceName: Substring {
    return Vmrun_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Mount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Vmrun_MountRequest>(),
        responseSerializer: ProtobufSerializer<Vmrun_MountReply>(),
        interceptors: self.interceptors?.makeMountInterceptors() ?? [],
        userFunction: self.mount(request:context:)
      )

    case "Umount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Vmrun_MountRequest>(),
        responseSerializer: ProtobufSerializer<Vmrun_MountReply>(),
        interceptors: self.interceptors?.makeUmountInterceptors() ?? [],
        userFunction: self.umount(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Vmrun_ServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Vmrun_ServiceServerInterceptorFactoryProtocol? { get }

  func mount(
    request: Vmrun_MountRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Vmrun_MountReply

  func umount(
    request: Vmrun_MountRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Vmrun_MountReply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Vmrun_ServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Vmrun_ServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Vmrun_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Vmrun_ServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Mount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Vmrun_MountRequest>(),
        responseSerializer: ProtobufSerializer<Vmrun_MountReply>(),
        interceptors: self.interceptors?.makeMountInterceptors() ?? [],
        wrapping: { try await self.mount(request: $0, context: $1) }
      )

    case "Umount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Vmrun_MountRequest>(),
        responseSerializer: ProtobufSerializer<Vmrun_MountReply>(),
        interceptors: self.interceptors?.makeUmountInterceptors() ?? [],
        wrapping: { try await self.umount(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Vmrun_ServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'mount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMountInterceptors() -> [ServerInterceptor<Vmrun_MountRequest, Vmrun_MountReply>]

  /// - Returns: Interceptors to use when handling 'umount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUmountInterceptors() -> [ServerInterceptor<Vmrun_MountRequest, Vmrun_MountReply>]
}

public enum Vmrun_ServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "vmrun.Service",
    methods: [
      Vmrun_ServiceServerMetadata.Methods.mount,
      Vmrun_ServiceServerMetadata.Methods.umount,
    ]
  )

  public enum Methods {
    public static let mount = GRPCMethodDescriptor(
      name: "Mount",
      path: "/vmrun.Service/Mount",
      type: GRPCCallType.unary
    )

    public static let umount = GRPCMethodDescriptor(
      name: "Umount",
      path: "/vmrun.Service/Umount",
      type: GRPCCallType.unary
    )
  }
}
