//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Caked_ServiceClient`, then call methods of this protocol to make API calls.
public protocol Caked_ServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? { get }

  func build(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_BuildRequest, Caked_Reply>

  func start(
    _ request: Caked_StartRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_StartRequest, Caked_Reply>

  func cakeCommand(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_CakedCommandRequest, Caked_Reply>

  func launch(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_LaunchRequest, Caked_Reply>

  func login(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_LoginRequest, Caked_Reply>

  func purge(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_PurgeRequest, Caked_Reply>

  func configure(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_ConfigureRequest, Caked_Reply>

  func waitIP(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_WaitIPRequest, Caked_Reply>

  func stop(
    _ request: Caked_StopRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_StopRequest, Caked_Reply>

  func remote(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_RemoteRequest, Caked_Reply>

  func networks(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_NetworkRequest, Caked_Reply>

  func info(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_InfoRequest, Caked_InfoReply>

  func execute(
    _ request: Caked_ExecuteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_ExecuteRequest, Caked_ExecuteReply>

  func shell(
    callOptions: CallOptions?,
    handler: @escaping (Caked_ShellResponse) -> Void
  ) -> BidirectionalStreamingCall<Caked_ShellRequest, Caked_ShellResponse>
}

extension Caked_ServiceClientProtocol {
  public var serviceName: String {
    return "caked.Service"
  }

  /// Sends a greeting
  ///
  /// - Parameters:
  ///   - request: Request to send to Build.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func build(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_BuildRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  /// Unary call to Start
  ///
  /// - Parameters:
  ///   - request: Request to send to Start.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func start(
    _ request: Caked_StartRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_StartRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  /// Unary call to CakeCommand
  ///
  /// - Parameters:
  ///   - request: Request to send to CakeCommand.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cakeCommand(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_CakedCommandRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.cakeCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? []
    )
  }

  /// Unary call to Launch
  ///
  /// - Parameters:
  ///   - request: Request to send to Launch.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func launch(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_LaunchRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  /// Unary call to Login
  ///
  /// - Parameters:
  ///   - request: Request to send to Login.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func login(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_LoginRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.login.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }

  /// Unary call to Purge
  ///
  /// - Parameters:
  ///   - request: Request to send to Purge.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func purge(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_PurgeRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.purge.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeInterceptors() ?? []
    )
  }

  /// Unary call to Configure
  ///
  /// - Parameters:
  ///   - request: Request to send to Configure.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func configure(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_ConfigureRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.configure.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConfigureInterceptors() ?? []
    )
  }

  /// Unary call to WaitIP
  ///
  /// - Parameters:
  ///   - request: Request to send to WaitIP.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func waitIP(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_WaitIPRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.waitIP.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitIPInterceptors() ?? []
    )
  }

  /// Unary call to Stop
  ///
  /// - Parameters:
  ///   - request: Request to send to Stop.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func stop(
    _ request: Caked_StopRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_StopRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.stop.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopInterceptors() ?? []
    )
  }

  /// Unary call to Remote
  ///
  /// - Parameters:
  ///   - request: Request to send to Remote.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func remote(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_RemoteRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.remote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoteInterceptors() ?? []
    )
  }

  /// Unary call to Networks
  ///
  /// - Parameters:
  ///   - request: Request to send to Networks.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func networks(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_NetworkRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.networks.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNetworksInterceptors() ?? []
    )
  }

  /// Unary call to Info
  ///
  /// - Parameters:
  ///   - request: Request to send to Info.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func info(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_InfoRequest, Caked_InfoReply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  /// Unary call to Execute
  ///
  /// - Parameters:
  ///   - request: Request to send to Execute.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func execute(
    _ request: Caked_ExecuteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_ExecuteRequest, Caked_ExecuteReply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to Shell
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func shell(
    callOptions: CallOptions? = nil,
    handler: @escaping (Caked_ShellResponse) -> Void
  ) -> BidirectionalStreamingCall<Caked_ShellRequest, Caked_ShellResponse> {
    return self.makeBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.shell.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Caked_ServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Caked_ServiceNIOClient")
public final class Caked_ServiceClient: Caked_ServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Caked_ServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the caked.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Caked_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Caked_ServiceNIOClient: Caked_ServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the caked.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Caked_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Caked_ServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? { get }

  func makeBuildCall(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_BuildRequest, Caked_Reply>

  func makeStartCall(
    _ request: Caked_StartRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_StartRequest, Caked_Reply>

  func makeCakeCommandCall(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_CakedCommandRequest, Caked_Reply>

  func makeLaunchCall(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_LaunchRequest, Caked_Reply>

  func makeLoginCall(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_LoginRequest, Caked_Reply>

  func makePurgeCall(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_PurgeRequest, Caked_Reply>

  func makeConfigureCall(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_ConfigureRequest, Caked_Reply>

  func makeWaitIpCall(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_WaitIPRequest, Caked_Reply>

  func makeStopCall(
    _ request: Caked_StopRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_StopRequest, Caked_Reply>

  func makeRemoteCall(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_RemoteRequest, Caked_Reply>

  func makeNetworksCall(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_NetworkRequest, Caked_Reply>

  func makeInfoCall(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_InfoRequest, Caked_InfoReply>

  func makeExecuteCall(
    _ request: Caked_ExecuteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_ExecuteRequest, Caked_ExecuteReply>

  func makeShellCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Caked_ShellRequest, Caked_ShellResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Caked_ServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Caked_ServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeBuildCall(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_BuildRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  public func makeStartCall(
    _ request: Caked_StartRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_StartRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  public func makeCakeCommandCall(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_CakedCommandRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.cakeCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? []
    )
  }

  public func makeLaunchCall(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_LaunchRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  public func makeLoginCall(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_LoginRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.login.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }

  public func makePurgeCall(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_PurgeRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.purge.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeInterceptors() ?? []
    )
  }

  public func makeConfigureCall(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_ConfigureRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.configure.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConfigureInterceptors() ?? []
    )
  }

  public func makeWaitIpCall(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_WaitIPRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.waitIP.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitIPInterceptors() ?? []
    )
  }

  public func makeStopCall(
    _ request: Caked_StopRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_StopRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.stop.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopInterceptors() ?? []
    )
  }

  public func makeRemoteCall(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_RemoteRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.remote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoteInterceptors() ?? []
    )
  }

  public func makeNetworksCall(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_NetworkRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.networks.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNetworksInterceptors() ?? []
    )
  }

  public func makeInfoCall(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_InfoRequest, Caked_InfoReply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  public func makeExecuteCall(
    _ request: Caked_ExecuteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_ExecuteRequest, Caked_ExecuteReply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func makeShellCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Caked_ShellRequest, Caked_ShellResponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.shell.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Caked_ServiceAsyncClientProtocol {
  public func build(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  public func start(
    _ request: Caked_StartRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  public func cakeCommand(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.cakeCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? []
    )
  }

  public func launch(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  public func login(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.login.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }

  public func purge(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.purge.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeInterceptors() ?? []
    )
  }

  public func configure(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.configure.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConfigureInterceptors() ?? []
    )
  }

  public func waitIP(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.waitIP.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitIPInterceptors() ?? []
    )
  }

  public func stop(
    _ request: Caked_StopRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.stop.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopInterceptors() ?? []
    )
  }

  public func remote(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.remote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoteInterceptors() ?? []
    )
  }

  public func networks(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.networks.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNetworksInterceptors() ?? []
    )
  }

  public func info(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_InfoReply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  public func execute(
    _ request: Caked_ExecuteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_ExecuteReply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func shell<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Caked_ShellResponse> where RequestStream: Sequence, RequestStream.Element == Caked_ShellRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.shell.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? []
    )
  }

  public func shell<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Caked_ShellResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Caked_ShellRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.shell.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Caked_ServiceAsyncClient: Caked_ServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Caked_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Caked_ServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'build'.
  func makeBuildInterceptors() -> [ClientInterceptor<Caked_BuildRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'start'.
  func makeStartInterceptors() -> [ClientInterceptor<Caked_StartRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'cakeCommand'.
  func makeCakeCommandInterceptors() -> [ClientInterceptor<Caked_CakedCommandRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'launch'.
  func makeLaunchInterceptors() -> [ClientInterceptor<Caked_LaunchRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'login'.
  func makeLoginInterceptors() -> [ClientInterceptor<Caked_LoginRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'purge'.
  func makePurgeInterceptors() -> [ClientInterceptor<Caked_PurgeRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'configure'.
  func makeConfigureInterceptors() -> [ClientInterceptor<Caked_ConfigureRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'waitIP'.
  func makeWaitIPInterceptors() -> [ClientInterceptor<Caked_WaitIPRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'stop'.
  func makeStopInterceptors() -> [ClientInterceptor<Caked_StopRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'remote'.
  func makeRemoteInterceptors() -> [ClientInterceptor<Caked_RemoteRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'networks'.
  func makeNetworksInterceptors() -> [ClientInterceptor<Caked_NetworkRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'info'.
  func makeInfoInterceptors() -> [ClientInterceptor<Caked_InfoRequest, Caked_InfoReply>]

  /// - Returns: Interceptors to use when invoking 'execute'.
  func makeExecuteInterceptors() -> [ClientInterceptor<Caked_ExecuteRequest, Caked_ExecuteReply>]

  /// - Returns: Interceptors to use when invoking 'shell'.
  func makeShellInterceptors() -> [ClientInterceptor<Caked_ShellRequest, Caked_ShellResponse>]
}

public enum Caked_ServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "caked.Service",
    methods: [
      Caked_ServiceClientMetadata.Methods.build,
      Caked_ServiceClientMetadata.Methods.start,
      Caked_ServiceClientMetadata.Methods.cakeCommand,
      Caked_ServiceClientMetadata.Methods.launch,
      Caked_ServiceClientMetadata.Methods.login,
      Caked_ServiceClientMetadata.Methods.purge,
      Caked_ServiceClientMetadata.Methods.configure,
      Caked_ServiceClientMetadata.Methods.waitIP,
      Caked_ServiceClientMetadata.Methods.stop,
      Caked_ServiceClientMetadata.Methods.remote,
      Caked_ServiceClientMetadata.Methods.networks,
      Caked_ServiceClientMetadata.Methods.info,
      Caked_ServiceClientMetadata.Methods.execute,
      Caked_ServiceClientMetadata.Methods.shell,
    ]
  )

  public enum Methods {
    public static let build = GRPCMethodDescriptor(
      name: "Build",
      path: "/caked.Service/Build",
      type: GRPCCallType.unary
    )

    public static let start = GRPCMethodDescriptor(
      name: "Start",
      path: "/caked.Service/Start",
      type: GRPCCallType.unary
    )

    public static let cakeCommand = GRPCMethodDescriptor(
      name: "CakeCommand",
      path: "/caked.Service/CakeCommand",
      type: GRPCCallType.unary
    )

    public static let launch = GRPCMethodDescriptor(
      name: "Launch",
      path: "/caked.Service/Launch",
      type: GRPCCallType.unary
    )

    public static let login = GRPCMethodDescriptor(
      name: "Login",
      path: "/caked.Service/Login",
      type: GRPCCallType.unary
    )

    public static let purge = GRPCMethodDescriptor(
      name: "Purge",
      path: "/caked.Service/Purge",
      type: GRPCCallType.unary
    )

    public static let configure = GRPCMethodDescriptor(
      name: "Configure",
      path: "/caked.Service/Configure",
      type: GRPCCallType.unary
    )

    public static let waitIP = GRPCMethodDescriptor(
      name: "WaitIP",
      path: "/caked.Service/WaitIP",
      type: GRPCCallType.unary
    )

    public static let stop = GRPCMethodDescriptor(
      name: "Stop",
      path: "/caked.Service/Stop",
      type: GRPCCallType.unary
    )

    public static let remote = GRPCMethodDescriptor(
      name: "Remote",
      path: "/caked.Service/Remote",
      type: GRPCCallType.unary
    )

    public static let networks = GRPCMethodDescriptor(
      name: "Networks",
      path: "/caked.Service/Networks",
      type: GRPCCallType.unary
    )

    public static let info = GRPCMethodDescriptor(
      name: "Info",
      path: "/caked.Service/Info",
      type: GRPCCallType.unary
    )

    public static let execute = GRPCMethodDescriptor(
      name: "Execute",
      path: "/caked.Service/Execute",
      type: GRPCCallType.unary
    )

    public static let shell = GRPCMethodDescriptor(
      name: "Shell",
      path: "/caked.Service/Shell",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Caked_ServiceProvider: CallHandlerProvider {
  var interceptors: Caked_ServiceServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting
  func build(request: Caked_BuildRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func start(request: Caked_StartRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func cakeCommand(request: Caked_CakedCommandRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func launch(request: Caked_LaunchRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func login(request: Caked_LoginRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func purge(request: Caked_PurgeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func configure(request: Caked_ConfigureRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func waitIP(request: Caked_WaitIPRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func stop(request: Caked_StopRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func remote(request: Caked_RemoteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func networks(request: Caked_NetworkRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func info(request: Caked_InfoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_InfoReply>

  func execute(request: Caked_ExecuteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_ExecuteReply>

  func shell(context: StreamingResponseCallContext<Caked_ShellResponse>) -> EventLoopFuture<(StreamEvent<Caked_ShellRequest>) -> Void>
}

extension Caked_ServiceProvider {
  public var serviceName: Substring {
    return Caked_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Build":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_BuildRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeBuildInterceptors() ?? [],
        userFunction: self.build(request:context:)
      )

    case "Start":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StartRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStartInterceptors() ?? [],
        userFunction: self.start(request:context:)
      )

    case "CakeCommand":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_CakedCommandRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? [],
        userFunction: self.cakeCommand(request:context:)
      )

    case "Launch":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LaunchRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLaunchInterceptors() ?? [],
        userFunction: self.launch(request:context:)
      )

    case "Login":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LoginRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLoginInterceptors() ?? [],
        userFunction: self.login(request:context:)
      )

    case "Purge":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_PurgeRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makePurgeInterceptors() ?? [],
        userFunction: self.purge(request:context:)
      )

    case "Configure":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ConfigureRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeConfigureInterceptors() ?? [],
        userFunction: self.configure(request:context:)
      )

    case "WaitIP":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_WaitIPRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeWaitIPInterceptors() ?? [],
        userFunction: self.waitIP(request:context:)
      )

    case "Stop":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StopRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStopInterceptors() ?? [],
        userFunction: self.stop(request:context:)
      )

    case "Remote":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RemoteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeRemoteInterceptors() ?? [],
        userFunction: self.remote(request:context:)
      )

    case "Networks":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_NetworkRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeNetworksInterceptors() ?? [],
        userFunction: self.networks(request:context:)
      )

    case "Info":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_InfoRequest>(),
        responseSerializer: ProtobufSerializer<Caked_InfoReply>(),
        interceptors: self.interceptors?.makeInfoInterceptors() ?? [],
        userFunction: self.info(request:context:)
      )

    case "Execute":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ExecuteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_ExecuteReply>(),
        interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
        userFunction: self.execute(request:context:)
      )

    case "Shell":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ShellRequest>(),
        responseSerializer: ProtobufSerializer<Caked_ShellResponse>(),
        interceptors: self.interceptors?.makeShellInterceptors() ?? [],
        observerFactory: self.shell(context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Caked_ServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Caked_ServiceServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting
  func build(
    request: Caked_BuildRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func start(
    request: Caked_StartRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func cakeCommand(
    request: Caked_CakedCommandRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func launch(
    request: Caked_LaunchRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func login(
    request: Caked_LoginRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func purge(
    request: Caked_PurgeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func configure(
    request: Caked_ConfigureRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func waitIP(
    request: Caked_WaitIPRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func stop(
    request: Caked_StopRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func remote(
    request: Caked_RemoteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func networks(
    request: Caked_NetworkRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func info(
    request: Caked_InfoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_InfoReply

  func execute(
    request: Caked_ExecuteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_ExecuteReply

  func shell(
    requestStream: GRPCAsyncRequestStream<Caked_ShellRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Caked_ShellResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Caked_ServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Caked_ServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Caked_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Caked_ServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Build":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_BuildRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeBuildInterceptors() ?? [],
        wrapping: { try await self.build(request: $0, context: $1) }
      )

    case "Start":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StartRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStartInterceptors() ?? [],
        wrapping: { try await self.start(request: $0, context: $1) }
      )

    case "CakeCommand":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_CakedCommandRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? [],
        wrapping: { try await self.cakeCommand(request: $0, context: $1) }
      )

    case "Launch":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LaunchRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLaunchInterceptors() ?? [],
        wrapping: { try await self.launch(request: $0, context: $1) }
      )

    case "Login":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LoginRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLoginInterceptors() ?? [],
        wrapping: { try await self.login(request: $0, context: $1) }
      )

    case "Purge":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_PurgeRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makePurgeInterceptors() ?? [],
        wrapping: { try await self.purge(request: $0, context: $1) }
      )

    case "Configure":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ConfigureRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeConfigureInterceptors() ?? [],
        wrapping: { try await self.configure(request: $0, context: $1) }
      )

    case "WaitIP":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_WaitIPRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeWaitIPInterceptors() ?? [],
        wrapping: { try await self.waitIP(request: $0, context: $1) }
      )

    case "Stop":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StopRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStopInterceptors() ?? [],
        wrapping: { try await self.stop(request: $0, context: $1) }
      )

    case "Remote":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RemoteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeRemoteInterceptors() ?? [],
        wrapping: { try await self.remote(request: $0, context: $1) }
      )

    case "Networks":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_NetworkRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeNetworksInterceptors() ?? [],
        wrapping: { try await self.networks(request: $0, context: $1) }
      )

    case "Info":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_InfoRequest>(),
        responseSerializer: ProtobufSerializer<Caked_InfoReply>(),
        interceptors: self.interceptors?.makeInfoInterceptors() ?? [],
        wrapping: { try await self.info(request: $0, context: $1) }
      )

    case "Execute":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ExecuteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_ExecuteReply>(),
        interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
        wrapping: { try await self.execute(request: $0, context: $1) }
      )

    case "Shell":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ShellRequest>(),
        responseSerializer: ProtobufSerializer<Caked_ShellResponse>(),
        interceptors: self.interceptors?.makeShellInterceptors() ?? [],
        wrapping: { try await self.shell(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Caked_ServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'build'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeBuildInterceptors() -> [ServerInterceptor<Caked_BuildRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'start'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStartInterceptors() -> [ServerInterceptor<Caked_StartRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'cakeCommand'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCakeCommandInterceptors() -> [ServerInterceptor<Caked_CakedCommandRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'launch'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLaunchInterceptors() -> [ServerInterceptor<Caked_LaunchRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'login'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLoginInterceptors() -> [ServerInterceptor<Caked_LoginRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'purge'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePurgeInterceptors() -> [ServerInterceptor<Caked_PurgeRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'configure'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeConfigureInterceptors() -> [ServerInterceptor<Caked_ConfigureRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'waitIP'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeWaitIPInterceptors() -> [ServerInterceptor<Caked_WaitIPRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'stop'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStopInterceptors() -> [ServerInterceptor<Caked_StopRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'remote'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRemoteInterceptors() -> [ServerInterceptor<Caked_RemoteRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'networks'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeNetworksInterceptors() -> [ServerInterceptor<Caked_NetworkRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'info'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeInfoInterceptors() -> [ServerInterceptor<Caked_InfoRequest, Caked_InfoReply>]

  /// - Returns: Interceptors to use when handling 'execute'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeExecuteInterceptors() -> [ServerInterceptor<Caked_ExecuteRequest, Caked_ExecuteReply>]

  /// - Returns: Interceptors to use when handling 'shell'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeShellInterceptors() -> [ServerInterceptor<Caked_ShellRequest, Caked_ShellResponse>]
}

public enum Caked_ServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "caked.Service",
    methods: [
      Caked_ServiceServerMetadata.Methods.build,
      Caked_ServiceServerMetadata.Methods.start,
      Caked_ServiceServerMetadata.Methods.cakeCommand,
      Caked_ServiceServerMetadata.Methods.launch,
      Caked_ServiceServerMetadata.Methods.login,
      Caked_ServiceServerMetadata.Methods.purge,
      Caked_ServiceServerMetadata.Methods.configure,
      Caked_ServiceServerMetadata.Methods.waitIP,
      Caked_ServiceServerMetadata.Methods.stop,
      Caked_ServiceServerMetadata.Methods.remote,
      Caked_ServiceServerMetadata.Methods.networks,
      Caked_ServiceServerMetadata.Methods.info,
      Caked_ServiceServerMetadata.Methods.execute,
      Caked_ServiceServerMetadata.Methods.shell,
    ]
  )

  public enum Methods {
    public static let build = GRPCMethodDescriptor(
      name: "Build",
      path: "/caked.Service/Build",
      type: GRPCCallType.unary
    )

    public static let start = GRPCMethodDescriptor(
      name: "Start",
      path: "/caked.Service/Start",
      type: GRPCCallType.unary
    )

    public static let cakeCommand = GRPCMethodDescriptor(
      name: "CakeCommand",
      path: "/caked.Service/CakeCommand",
      type: GRPCCallType.unary
    )

    public static let launch = GRPCMethodDescriptor(
      name: "Launch",
      path: "/caked.Service/Launch",
      type: GRPCCallType.unary
    )

    public static let login = GRPCMethodDescriptor(
      name: "Login",
      path: "/caked.Service/Login",
      type: GRPCCallType.unary
    )

    public static let purge = GRPCMethodDescriptor(
      name: "Purge",
      path: "/caked.Service/Purge",
      type: GRPCCallType.unary
    )

    public static let configure = GRPCMethodDescriptor(
      name: "Configure",
      path: "/caked.Service/Configure",
      type: GRPCCallType.unary
    )

    public static let waitIP = GRPCMethodDescriptor(
      name: "WaitIP",
      path: "/caked.Service/WaitIP",
      type: GRPCCallType.unary
    )

    public static let stop = GRPCMethodDescriptor(
      name: "Stop",
      path: "/caked.Service/Stop",
      type: GRPCCallType.unary
    )

    public static let remote = GRPCMethodDescriptor(
      name: "Remote",
      path: "/caked.Service/Remote",
      type: GRPCCallType.unary
    )

    public static let networks = GRPCMethodDescriptor(
      name: "Networks",
      path: "/caked.Service/Networks",
      type: GRPCCallType.unary
    )

    public static let info = GRPCMethodDescriptor(
      name: "Info",
      path: "/caked.Service/Info",
      type: GRPCCallType.unary
    )

    public static let execute = GRPCMethodDescriptor(
      name: "Execute",
      path: "/caked.Service/Execute",
      type: GRPCCallType.unary
    )

    public static let shell = GRPCMethodDescriptor(
      name: "Shell",
      path: "/caked.Service/Shell",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
