//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Tartd_ServiceClient`, then call methods of this protocol to make API calls.
public protocol Tartd_ServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? { get }

  func build(
    _ request: Tartd_BuildRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Tartd_BuildRequest, Tartd_TartReply>

  func start(
    _ request: Tartd_StartRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Tartd_StartRequest, Tartd_TartReply>

  func tartCommand(
    _ request: Tartd_TartCommandRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Tartd_TartCommandRequest, Tartd_TartReply>

  func launch(
    _ request: Tartd_LaunchRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Tartd_LaunchRequest, Tartd_TartReply>

  func prune(
    _ request: Tartd_PruneRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Tartd_PruneRequest, Tartd_TartReply>
}

extension Tartd_ServiceClientProtocol {
  public var serviceName: String {
    return "tartd.Service"
  }

  /// Sends a greeting
  ///
  /// - Parameters:
  ///   - request: Request to send to Build.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func build(
    _ request: Tartd_BuildRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Tartd_BuildRequest, Tartd_TartReply> {
    return self.makeUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  /// Unary call to Start
  ///
  /// - Parameters:
  ///   - request: Request to send to Start.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func start(
    _ request: Tartd_StartRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Tartd_StartRequest, Tartd_TartReply> {
    return self.makeUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  /// Unary call to TartCommand
  ///
  /// - Parameters:
  ///   - request: Request to send to TartCommand.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func tartCommand(
    _ request: Tartd_TartCommandRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Tartd_TartCommandRequest, Tartd_TartReply> {
    return self.makeUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.tartCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTartCommandInterceptors() ?? []
    )
  }

  /// Unary call to Launch
  ///
  /// - Parameters:
  ///   - request: Request to send to Launch.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func launch(
    _ request: Tartd_LaunchRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Tartd_LaunchRequest, Tartd_TartReply> {
    return self.makeUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  /// Unary call to Prune
  ///
  /// - Parameters:
  ///   - request: Request to send to Prune.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func prune(
    _ request: Tartd_PruneRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Tartd_PruneRequest, Tartd_TartReply> {
    return self.makeUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.prune.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePruneInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Tartd_ServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Tartd_ServiceNIOClient")
public final class Tartd_ServiceClient: Tartd_ServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Tartd_ServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the tartd.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Tartd_ServiceNIOClient: Tartd_ServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Tartd_ServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the tartd.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Tartd_ServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? { get }

  func makeBuildCall(
    _ request: Tartd_BuildRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Tartd_BuildRequest, Tartd_TartReply>

  func makeStartCall(
    _ request: Tartd_StartRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Tartd_StartRequest, Tartd_TartReply>

  func makeTartCommandCall(
    _ request: Tartd_TartCommandRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Tartd_TartCommandRequest, Tartd_TartReply>

  func makeLaunchCall(
    _ request: Tartd_LaunchRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Tartd_LaunchRequest, Tartd_TartReply>

  func makePruneCall(
    _ request: Tartd_PruneRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Tartd_PruneRequest, Tartd_TartReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Tartd_ServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Tartd_ServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeBuildCall(
    _ request: Tartd_BuildRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Tartd_BuildRequest, Tartd_TartReply> {
    return self.makeAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  public func makeStartCall(
    _ request: Tartd_StartRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Tartd_StartRequest, Tartd_TartReply> {
    return self.makeAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  public func makeTartCommandCall(
    _ request: Tartd_TartCommandRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Tartd_TartCommandRequest, Tartd_TartReply> {
    return self.makeAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.tartCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTartCommandInterceptors() ?? []
    )
  }

  public func makeLaunchCall(
    _ request: Tartd_LaunchRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Tartd_LaunchRequest, Tartd_TartReply> {
    return self.makeAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  public func makePruneCall(
    _ request: Tartd_PruneRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Tartd_PruneRequest, Tartd_TartReply> {
    return self.makeAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.prune.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePruneInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Tartd_ServiceAsyncClientProtocol {
  public func build(
    _ request: Tartd_BuildRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Tartd_TartReply {
    return try await self.performAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  public func start(
    _ request: Tartd_StartRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Tartd_TartReply {
    return try await self.performAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  public func tartCommand(
    _ request: Tartd_TartCommandRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Tartd_TartReply {
    return try await self.performAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.tartCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTartCommandInterceptors() ?? []
    )
  }

  public func launch(
    _ request: Tartd_LaunchRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Tartd_TartReply {
    return try await self.performAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  public func prune(
    _ request: Tartd_PruneRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Tartd_TartReply {
    return try await self.performAsyncUnaryCall(
      path: Tartd_ServiceClientMetadata.Methods.prune.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePruneInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Tartd_ServiceAsyncClient: Tartd_ServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Tartd_ServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Tartd_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Tartd_ServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'build'.
  func makeBuildInterceptors() -> [ClientInterceptor<Tartd_BuildRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when invoking 'start'.
  func makeStartInterceptors() -> [ClientInterceptor<Tartd_StartRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when invoking 'tartCommand'.
  func makeTartCommandInterceptors() -> [ClientInterceptor<Tartd_TartCommandRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when invoking 'launch'.
  func makeLaunchInterceptors() -> [ClientInterceptor<Tartd_LaunchRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when invoking 'prune'.
  func makePruneInterceptors() -> [ClientInterceptor<Tartd_PruneRequest, Tartd_TartReply>]
}

public enum Tartd_ServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "tartd.Service",
    methods: [
      Tartd_ServiceClientMetadata.Methods.build,
      Tartd_ServiceClientMetadata.Methods.start,
      Tartd_ServiceClientMetadata.Methods.tartCommand,
      Tartd_ServiceClientMetadata.Methods.launch,
      Tartd_ServiceClientMetadata.Methods.prune,
    ]
  )

  public enum Methods {
    public static let build = GRPCMethodDescriptor(
      name: "Build",
      path: "/tartd.Service/Build",
      type: GRPCCallType.unary
    )

    public static let start = GRPCMethodDescriptor(
      name: "Start",
      path: "/tartd.Service/Start",
      type: GRPCCallType.unary
    )

    public static let tartCommand = GRPCMethodDescriptor(
      name: "TartCommand",
      path: "/tartd.Service/TartCommand",
      type: GRPCCallType.unary
    )

    public static let launch = GRPCMethodDescriptor(
      name: "Launch",
      path: "/tartd.Service/Launch",
      type: GRPCCallType.unary
    )

    public static let prune = GRPCMethodDescriptor(
      name: "Prune",
      path: "/tartd.Service/Prune",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Tartd_ServiceProvider: CallHandlerProvider {
  var interceptors: Tartd_ServiceServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting
  func build(request: Tartd_BuildRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Tartd_TartReply>

  func start(request: Tartd_StartRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Tartd_TartReply>

  func tartCommand(request: Tartd_TartCommandRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Tartd_TartReply>

  func launch(request: Tartd_LaunchRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Tartd_TartReply>

  func prune(request: Tartd_PruneRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Tartd_TartReply>
}

extension Tartd_ServiceProvider {
  public var serviceName: Substring {
    return Tartd_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Build":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_BuildRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeBuildInterceptors() ?? [],
        userFunction: self.build(request:context:)
      )

    case "Start":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_StartRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeStartInterceptors() ?? [],
        userFunction: self.start(request:context:)
      )

    case "TartCommand":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_TartCommandRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeTartCommandInterceptors() ?? [],
        userFunction: self.tartCommand(request:context:)
      )

    case "Launch":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_LaunchRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeLaunchInterceptors() ?? [],
        userFunction: self.launch(request:context:)
      )

    case "Prune":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_PruneRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makePruneInterceptors() ?? [],
        userFunction: self.prune(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Tartd_ServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Tartd_ServiceServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting
  func build(
    request: Tartd_BuildRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Tartd_TartReply

  func start(
    request: Tartd_StartRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Tartd_TartReply

  func tartCommand(
    request: Tartd_TartCommandRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Tartd_TartReply

  func launch(
    request: Tartd_LaunchRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Tartd_TartReply

  func prune(
    request: Tartd_PruneRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Tartd_TartReply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Tartd_ServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Tartd_ServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Tartd_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Tartd_ServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Build":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_BuildRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeBuildInterceptors() ?? [],
        wrapping: { try await self.build(request: $0, context: $1) }
      )

    case "Start":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_StartRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeStartInterceptors() ?? [],
        wrapping: { try await self.start(request: $0, context: $1) }
      )

    case "TartCommand":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_TartCommandRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeTartCommandInterceptors() ?? [],
        wrapping: { try await self.tartCommand(request: $0, context: $1) }
      )

    case "Launch":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_LaunchRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makeLaunchInterceptors() ?? [],
        wrapping: { try await self.launch(request: $0, context: $1) }
      )

    case "Prune":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Tartd_PruneRequest>(),
        responseSerializer: ProtobufSerializer<Tartd_TartReply>(),
        interceptors: self.interceptors?.makePruneInterceptors() ?? [],
        wrapping: { try await self.prune(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Tartd_ServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'build'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeBuildInterceptors() -> [ServerInterceptor<Tartd_BuildRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when handling 'start'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStartInterceptors() -> [ServerInterceptor<Tartd_StartRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when handling 'tartCommand'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTartCommandInterceptors() -> [ServerInterceptor<Tartd_TartCommandRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when handling 'launch'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLaunchInterceptors() -> [ServerInterceptor<Tartd_LaunchRequest, Tartd_TartReply>]

  /// - Returns: Interceptors to use when handling 'prune'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePruneInterceptors() -> [ServerInterceptor<Tartd_PruneRequest, Tartd_TartReply>]
}

public enum Tartd_ServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "tartd.Service",
    methods: [
      Tartd_ServiceServerMetadata.Methods.build,
      Tartd_ServiceServerMetadata.Methods.start,
      Tartd_ServiceServerMetadata.Methods.tartCommand,
      Tartd_ServiceServerMetadata.Methods.launch,
      Tartd_ServiceServerMetadata.Methods.prune,
    ]
  )

  public enum Methods {
    public static let build = GRPCMethodDescriptor(
      name: "Build",
      path: "/tartd.Service/Build",
      type: GRPCCallType.unary
    )

    public static let start = GRPCMethodDescriptor(
      name: "Start",
      path: "/tartd.Service/Start",
      type: GRPCCallType.unary
    )

    public static let tartCommand = GRPCMethodDescriptor(
      name: "TartCommand",
      path: "/tartd.Service/TartCommand",
      type: GRPCCallType.unary
    )

    public static let launch = GRPCMethodDescriptor(
      name: "Launch",
      path: "/tartd.Service/Launch",
      type: GRPCCallType.unary
    )

    public static let prune = GRPCMethodDescriptor(
      name: "Prune",
      path: "/tartd.Service/Prune",
      type: GRPCCallType.unary
    )
  }
}
