//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Caked_ServiceClient`, then call methods of this protocol to make API calls.
public protocol Caked_ServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? { get }

  func build(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_BuildRequest, Caked_Reply>

  func start(
    _ request: Caked_StartRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_StartRequest, Caked_Reply>

  func cakeCommand(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_CakedCommandRequest, Caked_Reply>

  func launch(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_LaunchRequest, Caked_Reply>

  func login(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_LoginRequest, Caked_Reply>

  func logout(
    _ request: Caked_LogoutRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_LogoutRequest, Caked_Reply>

  func purge(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_PurgeRequest, Caked_Reply>

  func configure(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_ConfigureRequest, Caked_Reply>

  func waitIP(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_WaitIPRequest, Caked_Reply>

  func stop(
    _ request: Caked_StopRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_StopRequest, Caked_Reply>

  func list(
    _ request: Caked_ListRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_ListRequest, Caked_Reply>

  func delete(
    _ request: Caked_DeleteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_DeleteRequest, Caked_Reply>

  func image(
    _ request: Caked_ImageRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_ImageRequest, Caked_Reply>

  func remote(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_RemoteRequest, Caked_Reply>

  func networks(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_NetworkRequest, Caked_Reply>

  func template(
    _ request: Caked_TemplateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_TemplateRequest, Caked_Reply>

  func rename(
    _ request: Caked_RenameRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_RenameRequest, Caked_Reply>

  func info(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_InfoRequest, Caked_InfoReply>

  func run(
    _ request: Caked_RunCommand,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_RunCommand, Caked_RunReply>

  func execute(
    callOptions: CallOptions?,
    handler: @escaping (Caked_ExecuteResponse) -> Void
  ) -> BidirectionalStreamingCall<Caked_ExecuteRequest, Caked_ExecuteResponse>

  func mount(
    _ request: Caked_MountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_MountRequest, Caked_Reply>

  func umount(
    _ request: Caked_MountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Caked_MountRequest, Caked_Reply>
}

extension Caked_ServiceClientProtocol {
  public var serviceName: String {
    return "caked.Service"
  }

  /// Sends a greeting
  ///
  /// - Parameters:
  ///   - request: Request to send to Build.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func build(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_BuildRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  /// Unary call to Start
  ///
  /// - Parameters:
  ///   - request: Request to send to Start.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func start(
    _ request: Caked_StartRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_StartRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  /// Unary call to CakeCommand
  ///
  /// - Parameters:
  ///   - request: Request to send to CakeCommand.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cakeCommand(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_CakedCommandRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.cakeCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? []
    )
  }

  /// Unary call to Launch
  ///
  /// - Parameters:
  ///   - request: Request to send to Launch.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func launch(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_LaunchRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  /// Unary call to Login
  ///
  /// - Parameters:
  ///   - request: Request to send to Login.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func login(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_LoginRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.login.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }

  /// Unary call to Logout
  ///
  /// - Parameters:
  ///   - request: Request to send to Logout.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func logout(
    _ request: Caked_LogoutRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_LogoutRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.logout.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogoutInterceptors() ?? []
    )
  }

  /// Unary call to Purge
  ///
  /// - Parameters:
  ///   - request: Request to send to Purge.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func purge(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_PurgeRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.purge.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeInterceptors() ?? []
    )
  }

  /// Unary call to Configure
  ///
  /// - Parameters:
  ///   - request: Request to send to Configure.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func configure(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_ConfigureRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.configure.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConfigureInterceptors() ?? []
    )
  }

  /// Unary call to WaitIP
  ///
  /// - Parameters:
  ///   - request: Request to send to WaitIP.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func waitIP(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_WaitIPRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.waitIP.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitIPInterceptors() ?? []
    )
  }

  /// Unary call to Stop
  ///
  /// - Parameters:
  ///   - request: Request to send to Stop.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func stop(
    _ request: Caked_StopRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_StopRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.stop.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopInterceptors() ?? []
    )
  }

  /// Unary call to List
  ///
  /// - Parameters:
  ///   - request: Request to send to List.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func list(
    _ request: Caked_ListRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_ListRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.list.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListInterceptors() ?? []
    )
  }

  /// Unary call to Delete
  ///
  /// - Parameters:
  ///   - request: Request to send to Delete.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func delete(
    _ request: Caked_DeleteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_DeleteRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.delete.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteInterceptors() ?? []
    )
  }

  /// Unary call to Image
  ///
  /// - Parameters:
  ///   - request: Request to send to Image.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func image(
    _ request: Caked_ImageRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_ImageRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.image.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImageInterceptors() ?? []
    )
  }

  /// Unary call to Remote
  ///
  /// - Parameters:
  ///   - request: Request to send to Remote.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func remote(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_RemoteRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.remote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoteInterceptors() ?? []
    )
  }

  /// Unary call to Networks
  ///
  /// - Parameters:
  ///   - request: Request to send to Networks.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func networks(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_NetworkRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.networks.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNetworksInterceptors() ?? []
    )
  }

  /// Unary call to Template
  ///
  /// - Parameters:
  ///   - request: Request to send to Template.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func template(
    _ request: Caked_TemplateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_TemplateRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.template.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTemplateInterceptors() ?? []
    )
  }

  /// Unary call to Rename
  ///
  /// - Parameters:
  ///   - request: Request to send to Rename.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func rename(
    _ request: Caked_RenameRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_RenameRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.rename.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRenameInterceptors() ?? []
    )
  }

  /// Unary call to Info
  ///
  /// - Parameters:
  ///   - request: Request to send to Info.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func info(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_InfoRequest, Caked_InfoReply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  /// Unary call to Run
  ///
  /// - Parameters:
  ///   - request: Request to send to Run.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func run(
    _ request: Caked_RunCommand,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_RunCommand, Caked_RunReply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.run.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to Execute
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func execute(
    callOptions: CallOptions? = nil,
    handler: @escaping (Caked_ExecuteResponse) -> Void
  ) -> BidirectionalStreamingCall<Caked_ExecuteRequest, Caked_ExecuteResponse> {
    return self.makeBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary call to Mount
  ///
  /// - Parameters:
  ///   - request: Request to send to Mount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func mount(
    _ request: Caked_MountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_MountRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.mount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMountInterceptors() ?? []
    )
  }

  /// Unary call to Umount
  ///
  /// - Parameters:
  ///   - request: Request to send to Umount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func umount(
    _ request: Caked_MountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Caked_MountRequest, Caked_Reply> {
    return self.makeUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.umount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUmountInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Caked_ServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Caked_ServiceNIOClient")
public final class Caked_ServiceClient: Caked_ServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Caked_ServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the caked.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Caked_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Caked_ServiceNIOClient: Caked_ServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the caked.Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Caked_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Caked_ServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? { get }

  func makeBuildCall(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_BuildRequest, Caked_Reply>

  func makeStartCall(
    _ request: Caked_StartRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_StartRequest, Caked_Reply>

  func makeCakeCommandCall(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_CakedCommandRequest, Caked_Reply>

  func makeLaunchCall(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_LaunchRequest, Caked_Reply>

  func makeLoginCall(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_LoginRequest, Caked_Reply>

  func makeLogoutCall(
    _ request: Caked_LogoutRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_LogoutRequest, Caked_Reply>

  func makePurgeCall(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_PurgeRequest, Caked_Reply>

  func makeConfigureCall(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_ConfigureRequest, Caked_Reply>

  func makeWaitIpCall(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_WaitIPRequest, Caked_Reply>

  func makeStopCall(
    _ request: Caked_StopRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_StopRequest, Caked_Reply>

  func makeListCall(
    _ request: Caked_ListRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_ListRequest, Caked_Reply>

  func makeDeleteCall(
    _ request: Caked_DeleteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_DeleteRequest, Caked_Reply>

  func makeImageCall(
    _ request: Caked_ImageRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_ImageRequest, Caked_Reply>

  func makeRemoteCall(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_RemoteRequest, Caked_Reply>

  func makeNetworksCall(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_NetworkRequest, Caked_Reply>

  func makeTemplateCall(
    _ request: Caked_TemplateRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_TemplateRequest, Caked_Reply>

  func makeRenameCall(
    _ request: Caked_RenameRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_RenameRequest, Caked_Reply>

  func makeInfoCall(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_InfoRequest, Caked_InfoReply>

  func makeRunCall(
    _ request: Caked_RunCommand,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_RunCommand, Caked_RunReply>

  func makeExecuteCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Caked_ExecuteRequest, Caked_ExecuteResponse>

  func makeMountCall(
    _ request: Caked_MountRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_MountRequest, Caked_Reply>

  func makeUmountCall(
    _ request: Caked_MountRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Caked_MountRequest, Caked_Reply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Caked_ServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Caked_ServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeBuildCall(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_BuildRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  public func makeStartCall(
    _ request: Caked_StartRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_StartRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  public func makeCakeCommandCall(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_CakedCommandRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.cakeCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? []
    )
  }

  public func makeLaunchCall(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_LaunchRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  public func makeLoginCall(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_LoginRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.login.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }

  public func makeLogoutCall(
    _ request: Caked_LogoutRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_LogoutRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.logout.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogoutInterceptors() ?? []
    )
  }

  public func makePurgeCall(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_PurgeRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.purge.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeInterceptors() ?? []
    )
  }

  public func makeConfigureCall(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_ConfigureRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.configure.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConfigureInterceptors() ?? []
    )
  }

  public func makeWaitIpCall(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_WaitIPRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.waitIP.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitIPInterceptors() ?? []
    )
  }

  public func makeStopCall(
    _ request: Caked_StopRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_StopRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.stop.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopInterceptors() ?? []
    )
  }

  public func makeListCall(
    _ request: Caked_ListRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_ListRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.list.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListInterceptors() ?? []
    )
  }

  public func makeDeleteCall(
    _ request: Caked_DeleteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_DeleteRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.delete.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteInterceptors() ?? []
    )
  }

  public func makeImageCall(
    _ request: Caked_ImageRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_ImageRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.image.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImageInterceptors() ?? []
    )
  }

  public func makeRemoteCall(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_RemoteRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.remote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoteInterceptors() ?? []
    )
  }

  public func makeNetworksCall(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_NetworkRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.networks.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNetworksInterceptors() ?? []
    )
  }

  public func makeTemplateCall(
    _ request: Caked_TemplateRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_TemplateRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.template.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTemplateInterceptors() ?? []
    )
  }

  public func makeRenameCall(
    _ request: Caked_RenameRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_RenameRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.rename.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRenameInterceptors() ?? []
    )
  }

  public func makeInfoCall(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_InfoRequest, Caked_InfoReply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  public func makeRunCall(
    _ request: Caked_RunCommand,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_RunCommand, Caked_RunReply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.run.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunInterceptors() ?? []
    )
  }

  public func makeExecuteCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Caked_ExecuteRequest, Caked_ExecuteResponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func makeMountCall(
    _ request: Caked_MountRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_MountRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.mount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMountInterceptors() ?? []
    )
  }

  public func makeUmountCall(
    _ request: Caked_MountRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Caked_MountRequest, Caked_Reply> {
    return self.makeAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.umount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUmountInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Caked_ServiceAsyncClientProtocol {
  public func build(
    _ request: Caked_BuildRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.build.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBuildInterceptors() ?? []
    )
  }

  public func start(
    _ request: Caked_StartRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.start.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartInterceptors() ?? []
    )
  }

  public func cakeCommand(
    _ request: Caked_CakedCommandRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.cakeCommand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? []
    )
  }

  public func launch(
    _ request: Caked_LaunchRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.launch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLaunchInterceptors() ?? []
    )
  }

  public func login(
    _ request: Caked_LoginRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.login.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }

  public func logout(
    _ request: Caked_LogoutRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.logout.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogoutInterceptors() ?? []
    )
  }

  public func purge(
    _ request: Caked_PurgeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.purge.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeInterceptors() ?? []
    )
  }

  public func configure(
    _ request: Caked_ConfigureRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.configure.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConfigureInterceptors() ?? []
    )
  }

  public func waitIP(
    _ request: Caked_WaitIPRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.waitIP.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitIPInterceptors() ?? []
    )
  }

  public func stop(
    _ request: Caked_StopRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.stop.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopInterceptors() ?? []
    )
  }

  public func list(
    _ request: Caked_ListRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.list.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListInterceptors() ?? []
    )
  }

  public func delete(
    _ request: Caked_DeleteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.delete.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteInterceptors() ?? []
    )
  }

  public func image(
    _ request: Caked_ImageRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.image.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImageInterceptors() ?? []
    )
  }

  public func remote(
    _ request: Caked_RemoteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.remote.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoteInterceptors() ?? []
    )
  }

  public func networks(
    _ request: Caked_NetworkRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.networks.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNetworksInterceptors() ?? []
    )
  }

  public func template(
    _ request: Caked_TemplateRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.template.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTemplateInterceptors() ?? []
    )
  }

  public func rename(
    _ request: Caked_RenameRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.rename.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRenameInterceptors() ?? []
    )
  }

  public func info(
    _ request: Caked_InfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_InfoReply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  public func run(
    _ request: Caked_RunCommand,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_RunReply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.run.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunInterceptors() ?? []
    )
  }

  public func execute<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Caked_ExecuteResponse> where RequestStream: Sequence, RequestStream.Element == Caked_ExecuteRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func execute<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Caked_ExecuteResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Caked_ExecuteRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Caked_ServiceClientMetadata.Methods.execute.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func mount(
    _ request: Caked_MountRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.mount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMountInterceptors() ?? []
    )
  }

  public func umount(
    _ request: Caked_MountRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Caked_Reply {
    return try await self.performAsyncUnaryCall(
      path: Caked_ServiceClientMetadata.Methods.umount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUmountInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Caked_ServiceAsyncClient: Caked_ServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Caked_ServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Caked_ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Caked_ServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'build'.
  func makeBuildInterceptors() -> [ClientInterceptor<Caked_BuildRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'start'.
  func makeStartInterceptors() -> [ClientInterceptor<Caked_StartRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'cakeCommand'.
  func makeCakeCommandInterceptors() -> [ClientInterceptor<Caked_CakedCommandRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'launch'.
  func makeLaunchInterceptors() -> [ClientInterceptor<Caked_LaunchRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'login'.
  func makeLoginInterceptors() -> [ClientInterceptor<Caked_LoginRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'logout'.
  func makeLogoutInterceptors() -> [ClientInterceptor<Caked_LogoutRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'purge'.
  func makePurgeInterceptors() -> [ClientInterceptor<Caked_PurgeRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'configure'.
  func makeConfigureInterceptors() -> [ClientInterceptor<Caked_ConfigureRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'waitIP'.
  func makeWaitIPInterceptors() -> [ClientInterceptor<Caked_WaitIPRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'stop'.
  func makeStopInterceptors() -> [ClientInterceptor<Caked_StopRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'list'.
  func makeListInterceptors() -> [ClientInterceptor<Caked_ListRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'delete'.
  func makeDeleteInterceptors() -> [ClientInterceptor<Caked_DeleteRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'image'.
  func makeImageInterceptors() -> [ClientInterceptor<Caked_ImageRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'remote'.
  func makeRemoteInterceptors() -> [ClientInterceptor<Caked_RemoteRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'networks'.
  func makeNetworksInterceptors() -> [ClientInterceptor<Caked_NetworkRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'template'.
  func makeTemplateInterceptors() -> [ClientInterceptor<Caked_TemplateRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'rename'.
  func makeRenameInterceptors() -> [ClientInterceptor<Caked_RenameRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'info'.
  func makeInfoInterceptors() -> [ClientInterceptor<Caked_InfoRequest, Caked_InfoReply>]

  /// - Returns: Interceptors to use when invoking 'run'.
  func makeRunInterceptors() -> [ClientInterceptor<Caked_RunCommand, Caked_RunReply>]

  /// - Returns: Interceptors to use when invoking 'execute'.
  func makeExecuteInterceptors() -> [ClientInterceptor<Caked_ExecuteRequest, Caked_ExecuteResponse>]

  /// - Returns: Interceptors to use when invoking 'mount'.
  func makeMountInterceptors() -> [ClientInterceptor<Caked_MountRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when invoking 'umount'.
  func makeUmountInterceptors() -> [ClientInterceptor<Caked_MountRequest, Caked_Reply>]
}

public enum Caked_ServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "caked.Service",
    methods: [
      Caked_ServiceClientMetadata.Methods.build,
      Caked_ServiceClientMetadata.Methods.start,
      Caked_ServiceClientMetadata.Methods.cakeCommand,
      Caked_ServiceClientMetadata.Methods.launch,
      Caked_ServiceClientMetadata.Methods.login,
      Caked_ServiceClientMetadata.Methods.logout,
      Caked_ServiceClientMetadata.Methods.purge,
      Caked_ServiceClientMetadata.Methods.configure,
      Caked_ServiceClientMetadata.Methods.waitIP,
      Caked_ServiceClientMetadata.Methods.stop,
      Caked_ServiceClientMetadata.Methods.list,
      Caked_ServiceClientMetadata.Methods.delete,
      Caked_ServiceClientMetadata.Methods.image,
      Caked_ServiceClientMetadata.Methods.remote,
      Caked_ServiceClientMetadata.Methods.networks,
      Caked_ServiceClientMetadata.Methods.template,
      Caked_ServiceClientMetadata.Methods.rename,
      Caked_ServiceClientMetadata.Methods.info,
      Caked_ServiceClientMetadata.Methods.run,
      Caked_ServiceClientMetadata.Methods.execute,
      Caked_ServiceClientMetadata.Methods.mount,
      Caked_ServiceClientMetadata.Methods.umount,
    ]
  )

  public enum Methods {
    public static let build = GRPCMethodDescriptor(
      name: "Build",
      path: "/caked.Service/Build",
      type: GRPCCallType.unary
    )

    public static let start = GRPCMethodDescriptor(
      name: "Start",
      path: "/caked.Service/Start",
      type: GRPCCallType.unary
    )

    public static let cakeCommand = GRPCMethodDescriptor(
      name: "CakeCommand",
      path: "/caked.Service/CakeCommand",
      type: GRPCCallType.unary
    )

    public static let launch = GRPCMethodDescriptor(
      name: "Launch",
      path: "/caked.Service/Launch",
      type: GRPCCallType.unary
    )

    public static let login = GRPCMethodDescriptor(
      name: "Login",
      path: "/caked.Service/Login",
      type: GRPCCallType.unary
    )

    public static let logout = GRPCMethodDescriptor(
      name: "Logout",
      path: "/caked.Service/Logout",
      type: GRPCCallType.unary
    )

    public static let purge = GRPCMethodDescriptor(
      name: "Purge",
      path: "/caked.Service/Purge",
      type: GRPCCallType.unary
    )

    public static let configure = GRPCMethodDescriptor(
      name: "Configure",
      path: "/caked.Service/Configure",
      type: GRPCCallType.unary
    )

    public static let waitIP = GRPCMethodDescriptor(
      name: "WaitIP",
      path: "/caked.Service/WaitIP",
      type: GRPCCallType.unary
    )

    public static let stop = GRPCMethodDescriptor(
      name: "Stop",
      path: "/caked.Service/Stop",
      type: GRPCCallType.unary
    )

    public static let list = GRPCMethodDescriptor(
      name: "List",
      path: "/caked.Service/List",
      type: GRPCCallType.unary
    )

    public static let delete = GRPCMethodDescriptor(
      name: "Delete",
      path: "/caked.Service/Delete",
      type: GRPCCallType.unary
    )

    public static let image = GRPCMethodDescriptor(
      name: "Image",
      path: "/caked.Service/Image",
      type: GRPCCallType.unary
    )

    public static let remote = GRPCMethodDescriptor(
      name: "Remote",
      path: "/caked.Service/Remote",
      type: GRPCCallType.unary
    )

    public static let networks = GRPCMethodDescriptor(
      name: "Networks",
      path: "/caked.Service/Networks",
      type: GRPCCallType.unary
    )

    public static let template = GRPCMethodDescriptor(
      name: "Template",
      path: "/caked.Service/Template",
      type: GRPCCallType.unary
    )

    public static let rename = GRPCMethodDescriptor(
      name: "Rename",
      path: "/caked.Service/Rename",
      type: GRPCCallType.unary
    )

    public static let info = GRPCMethodDescriptor(
      name: "Info",
      path: "/caked.Service/Info",
      type: GRPCCallType.unary
    )

    public static let run = GRPCMethodDescriptor(
      name: "Run",
      path: "/caked.Service/Run",
      type: GRPCCallType.unary
    )

    public static let execute = GRPCMethodDescriptor(
      name: "Execute",
      path: "/caked.Service/Execute",
      type: GRPCCallType.bidirectionalStreaming
    )

    public static let mount = GRPCMethodDescriptor(
      name: "Mount",
      path: "/caked.Service/Mount",
      type: GRPCCallType.unary
    )

    public static let umount = GRPCMethodDescriptor(
      name: "Umount",
      path: "/caked.Service/Umount",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Caked_ServiceProvider: CallHandlerProvider {
  var interceptors: Caked_ServiceServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting
  func build(request: Caked_BuildRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func start(request: Caked_StartRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func cakeCommand(request: Caked_CakedCommandRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func launch(request: Caked_LaunchRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func login(request: Caked_LoginRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func logout(request: Caked_LogoutRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func purge(request: Caked_PurgeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func configure(request: Caked_ConfigureRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func waitIP(request: Caked_WaitIPRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func stop(request: Caked_StopRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func list(request: Caked_ListRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func delete(request: Caked_DeleteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func image(request: Caked_ImageRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func remote(request: Caked_RemoteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func networks(request: Caked_NetworkRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func template(request: Caked_TemplateRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func rename(request: Caked_RenameRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func info(request: Caked_InfoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_InfoReply>

  func run(request: Caked_RunCommand, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_RunReply>

  func execute(context: StreamingResponseCallContext<Caked_ExecuteResponse>) -> EventLoopFuture<(StreamEvent<Caked_ExecuteRequest>) -> Void>

  func mount(request: Caked_MountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>

  func umount(request: Caked_MountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Caked_Reply>
}

extension Caked_ServiceProvider {
  public var serviceName: Substring {
    return Caked_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Build":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_BuildRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeBuildInterceptors() ?? [],
        userFunction: self.build(request:context:)
      )

    case "Start":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StartRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStartInterceptors() ?? [],
        userFunction: self.start(request:context:)
      )

    case "CakeCommand":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_CakedCommandRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? [],
        userFunction: self.cakeCommand(request:context:)
      )

    case "Launch":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LaunchRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLaunchInterceptors() ?? [],
        userFunction: self.launch(request:context:)
      )

    case "Login":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LoginRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLoginInterceptors() ?? [],
        userFunction: self.login(request:context:)
      )

    case "Logout":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LogoutRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLogoutInterceptors() ?? [],
        userFunction: self.logout(request:context:)
      )

    case "Purge":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_PurgeRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makePurgeInterceptors() ?? [],
        userFunction: self.purge(request:context:)
      )

    case "Configure":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ConfigureRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeConfigureInterceptors() ?? [],
        userFunction: self.configure(request:context:)
      )

    case "WaitIP":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_WaitIPRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeWaitIPInterceptors() ?? [],
        userFunction: self.waitIP(request:context:)
      )

    case "Stop":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StopRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStopInterceptors() ?? [],
        userFunction: self.stop(request:context:)
      )

    case "List":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ListRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeListInterceptors() ?? [],
        userFunction: self.list(request:context:)
      )

    case "Delete":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_DeleteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeDeleteInterceptors() ?? [],
        userFunction: self.delete(request:context:)
      )

    case "Image":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ImageRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeImageInterceptors() ?? [],
        userFunction: self.image(request:context:)
      )

    case "Remote":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RemoteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeRemoteInterceptors() ?? [],
        userFunction: self.remote(request:context:)
      )

    case "Networks":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_NetworkRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeNetworksInterceptors() ?? [],
        userFunction: self.networks(request:context:)
      )

    case "Template":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_TemplateRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeTemplateInterceptors() ?? [],
        userFunction: self.template(request:context:)
      )

    case "Rename":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RenameRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeRenameInterceptors() ?? [],
        userFunction: self.rename(request:context:)
      )

    case "Info":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_InfoRequest>(),
        responseSerializer: ProtobufSerializer<Caked_InfoReply>(),
        interceptors: self.interceptors?.makeInfoInterceptors() ?? [],
        userFunction: self.info(request:context:)
      )

    case "Run":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RunCommand>(),
        responseSerializer: ProtobufSerializer<Caked_RunReply>(),
        interceptors: self.interceptors?.makeRunInterceptors() ?? [],
        userFunction: self.run(request:context:)
      )

    case "Execute":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ExecuteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_ExecuteResponse>(),
        interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
        observerFactory: self.execute(context:)
      )

    case "Mount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_MountRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeMountInterceptors() ?? [],
        userFunction: self.mount(request:context:)
      )

    case "Umount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_MountRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeUmountInterceptors() ?? [],
        userFunction: self.umount(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Caked_ServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Caked_ServiceServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting
  func build(
    request: Caked_BuildRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func start(
    request: Caked_StartRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func cakeCommand(
    request: Caked_CakedCommandRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func launch(
    request: Caked_LaunchRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func login(
    request: Caked_LoginRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func logout(
    request: Caked_LogoutRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func purge(
    request: Caked_PurgeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func configure(
    request: Caked_ConfigureRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func waitIP(
    request: Caked_WaitIPRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func stop(
    request: Caked_StopRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func list(
    request: Caked_ListRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func delete(
    request: Caked_DeleteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func image(
    request: Caked_ImageRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func remote(
    request: Caked_RemoteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func networks(
    request: Caked_NetworkRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func template(
    request: Caked_TemplateRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func rename(
    request: Caked_RenameRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func info(
    request: Caked_InfoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_InfoReply

  func run(
    request: Caked_RunCommand,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_RunReply

  func execute(
    requestStream: GRPCAsyncRequestStream<Caked_ExecuteRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Caked_ExecuteResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws

  func mount(
    request: Caked_MountRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply

  func umount(
    request: Caked_MountRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Caked_Reply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Caked_ServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Caked_ServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Caked_ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Caked_ServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Build":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_BuildRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeBuildInterceptors() ?? [],
        wrapping: { try await self.build(request: $0, context: $1) }
      )

    case "Start":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StartRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStartInterceptors() ?? [],
        wrapping: { try await self.start(request: $0, context: $1) }
      )

    case "CakeCommand":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_CakedCommandRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeCakeCommandInterceptors() ?? [],
        wrapping: { try await self.cakeCommand(request: $0, context: $1) }
      )

    case "Launch":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LaunchRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLaunchInterceptors() ?? [],
        wrapping: { try await self.launch(request: $0, context: $1) }
      )

    case "Login":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LoginRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLoginInterceptors() ?? [],
        wrapping: { try await self.login(request: $0, context: $1) }
      )

    case "Logout":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_LogoutRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeLogoutInterceptors() ?? [],
        wrapping: { try await self.logout(request: $0, context: $1) }
      )

    case "Purge":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_PurgeRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makePurgeInterceptors() ?? [],
        wrapping: { try await self.purge(request: $0, context: $1) }
      )

    case "Configure":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ConfigureRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeConfigureInterceptors() ?? [],
        wrapping: { try await self.configure(request: $0, context: $1) }
      )

    case "WaitIP":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_WaitIPRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeWaitIPInterceptors() ?? [],
        wrapping: { try await self.waitIP(request: $0, context: $1) }
      )

    case "Stop":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_StopRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeStopInterceptors() ?? [],
        wrapping: { try await self.stop(request: $0, context: $1) }
      )

    case "List":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ListRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeListInterceptors() ?? [],
        wrapping: { try await self.list(request: $0, context: $1) }
      )

    case "Delete":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_DeleteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeDeleteInterceptors() ?? [],
        wrapping: { try await self.delete(request: $0, context: $1) }
      )

    case "Image":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ImageRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeImageInterceptors() ?? [],
        wrapping: { try await self.image(request: $0, context: $1) }
      )

    case "Remote":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RemoteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeRemoteInterceptors() ?? [],
        wrapping: { try await self.remote(request: $0, context: $1) }
      )

    case "Networks":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_NetworkRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeNetworksInterceptors() ?? [],
        wrapping: { try await self.networks(request: $0, context: $1) }
      )

    case "Template":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_TemplateRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeTemplateInterceptors() ?? [],
        wrapping: { try await self.template(request: $0, context: $1) }
      )

    case "Rename":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RenameRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeRenameInterceptors() ?? [],
        wrapping: { try await self.rename(request: $0, context: $1) }
      )

    case "Info":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_InfoRequest>(),
        responseSerializer: ProtobufSerializer<Caked_InfoReply>(),
        interceptors: self.interceptors?.makeInfoInterceptors() ?? [],
        wrapping: { try await self.info(request: $0, context: $1) }
      )

    case "Run":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_RunCommand>(),
        responseSerializer: ProtobufSerializer<Caked_RunReply>(),
        interceptors: self.interceptors?.makeRunInterceptors() ?? [],
        wrapping: { try await self.run(request: $0, context: $1) }
      )

    case "Execute":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_ExecuteRequest>(),
        responseSerializer: ProtobufSerializer<Caked_ExecuteResponse>(),
        interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
        wrapping: { try await self.execute(requestStream: $0, responseStream: $1, context: $2) }
      )

    case "Mount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_MountRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeMountInterceptors() ?? [],
        wrapping: { try await self.mount(request: $0, context: $1) }
      )

    case "Umount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Caked_MountRequest>(),
        responseSerializer: ProtobufSerializer<Caked_Reply>(),
        interceptors: self.interceptors?.makeUmountInterceptors() ?? [],
        wrapping: { try await self.umount(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Caked_ServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'build'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeBuildInterceptors() -> [ServerInterceptor<Caked_BuildRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'start'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStartInterceptors() -> [ServerInterceptor<Caked_StartRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'cakeCommand'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCakeCommandInterceptors() -> [ServerInterceptor<Caked_CakedCommandRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'launch'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLaunchInterceptors() -> [ServerInterceptor<Caked_LaunchRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'login'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLoginInterceptors() -> [ServerInterceptor<Caked_LoginRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'logout'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLogoutInterceptors() -> [ServerInterceptor<Caked_LogoutRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'purge'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePurgeInterceptors() -> [ServerInterceptor<Caked_PurgeRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'configure'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeConfigureInterceptors() -> [ServerInterceptor<Caked_ConfigureRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'waitIP'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeWaitIPInterceptors() -> [ServerInterceptor<Caked_WaitIPRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'stop'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStopInterceptors() -> [ServerInterceptor<Caked_StopRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'list'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListInterceptors() -> [ServerInterceptor<Caked_ListRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'delete'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteInterceptors() -> [ServerInterceptor<Caked_DeleteRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'image'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeImageInterceptors() -> [ServerInterceptor<Caked_ImageRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'remote'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRemoteInterceptors() -> [ServerInterceptor<Caked_RemoteRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'networks'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeNetworksInterceptors() -> [ServerInterceptor<Caked_NetworkRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'template'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTemplateInterceptors() -> [ServerInterceptor<Caked_TemplateRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'rename'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRenameInterceptors() -> [ServerInterceptor<Caked_RenameRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'info'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeInfoInterceptors() -> [ServerInterceptor<Caked_InfoRequest, Caked_InfoReply>]

  /// - Returns: Interceptors to use when handling 'run'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRunInterceptors() -> [ServerInterceptor<Caked_RunCommand, Caked_RunReply>]

  /// - Returns: Interceptors to use when handling 'execute'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeExecuteInterceptors() -> [ServerInterceptor<Caked_ExecuteRequest, Caked_ExecuteResponse>]

  /// - Returns: Interceptors to use when handling 'mount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMountInterceptors() -> [ServerInterceptor<Caked_MountRequest, Caked_Reply>]

  /// - Returns: Interceptors to use when handling 'umount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUmountInterceptors() -> [ServerInterceptor<Caked_MountRequest, Caked_Reply>]
}

public enum Caked_ServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "caked.Service",
    methods: [
      Caked_ServiceServerMetadata.Methods.build,
      Caked_ServiceServerMetadata.Methods.start,
      Caked_ServiceServerMetadata.Methods.cakeCommand,
      Caked_ServiceServerMetadata.Methods.launch,
      Caked_ServiceServerMetadata.Methods.login,
      Caked_ServiceServerMetadata.Methods.logout,
      Caked_ServiceServerMetadata.Methods.purge,
      Caked_ServiceServerMetadata.Methods.configure,
      Caked_ServiceServerMetadata.Methods.waitIP,
      Caked_ServiceServerMetadata.Methods.stop,
      Caked_ServiceServerMetadata.Methods.list,
      Caked_ServiceServerMetadata.Methods.delete,
      Caked_ServiceServerMetadata.Methods.image,
      Caked_ServiceServerMetadata.Methods.remote,
      Caked_ServiceServerMetadata.Methods.networks,
      Caked_ServiceServerMetadata.Methods.template,
      Caked_ServiceServerMetadata.Methods.rename,
      Caked_ServiceServerMetadata.Methods.info,
      Caked_ServiceServerMetadata.Methods.run,
      Caked_ServiceServerMetadata.Methods.execute,
      Caked_ServiceServerMetadata.Methods.mount,
      Caked_ServiceServerMetadata.Methods.umount,
    ]
  )

  public enum Methods {
    public static let build = GRPCMethodDescriptor(
      name: "Build",
      path: "/caked.Service/Build",
      type: GRPCCallType.unary
    )

    public static let start = GRPCMethodDescriptor(
      name: "Start",
      path: "/caked.Service/Start",
      type: GRPCCallType.unary
    )

    public static let cakeCommand = GRPCMethodDescriptor(
      name: "CakeCommand",
      path: "/caked.Service/CakeCommand",
      type: GRPCCallType.unary
    )

    public static let launch = GRPCMethodDescriptor(
      name: "Launch",
      path: "/caked.Service/Launch",
      type: GRPCCallType.unary
    )

    public static let login = GRPCMethodDescriptor(
      name: "Login",
      path: "/caked.Service/Login",
      type: GRPCCallType.unary
    )

    public static let logout = GRPCMethodDescriptor(
      name: "Logout",
      path: "/caked.Service/Logout",
      type: GRPCCallType.unary
    )

    public static let purge = GRPCMethodDescriptor(
      name: "Purge",
      path: "/caked.Service/Purge",
      type: GRPCCallType.unary
    )

    public static let configure = GRPCMethodDescriptor(
      name: "Configure",
      path: "/caked.Service/Configure",
      type: GRPCCallType.unary
    )

    public static let waitIP = GRPCMethodDescriptor(
      name: "WaitIP",
      path: "/caked.Service/WaitIP",
      type: GRPCCallType.unary
    )

    public static let stop = GRPCMethodDescriptor(
      name: "Stop",
      path: "/caked.Service/Stop",
      type: GRPCCallType.unary
    )

    public static let list = GRPCMethodDescriptor(
      name: "List",
      path: "/caked.Service/List",
      type: GRPCCallType.unary
    )

    public static let delete = GRPCMethodDescriptor(
      name: "Delete",
      path: "/caked.Service/Delete",
      type: GRPCCallType.unary
    )

    public static let image = GRPCMethodDescriptor(
      name: "Image",
      path: "/caked.Service/Image",
      type: GRPCCallType.unary
    )

    public static let remote = GRPCMethodDescriptor(
      name: "Remote",
      path: "/caked.Service/Remote",
      type: GRPCCallType.unary
    )

    public static let networks = GRPCMethodDescriptor(
      name: "Networks",
      path: "/caked.Service/Networks",
      type: GRPCCallType.unary
    )

    public static let template = GRPCMethodDescriptor(
      name: "Template",
      path: "/caked.Service/Template",
      type: GRPCCallType.unary
    )

    public static let rename = GRPCMethodDescriptor(
      name: "Rename",
      path: "/caked.Service/Rename",
      type: GRPCCallType.unary
    )

    public static let info = GRPCMethodDescriptor(
      name: "Info",
      path: "/caked.Service/Info",
      type: GRPCCallType.unary
    )

    public static let run = GRPCMethodDescriptor(
      name: "Run",
      path: "/caked.Service/Run",
      type: GRPCCallType.unary
    )

    public static let execute = GRPCMethodDescriptor(
      name: "Execute",
      path: "/caked.Service/Execute",
      type: GRPCCallType.bidirectionalStreaming
    )

    public static let mount = GRPCMethodDescriptor(
      name: "Mount",
      path: "/caked.Service/Mount",
      type: GRPCCallType.unary
    )

    public static let umount = GRPCMethodDescriptor(
      name: "Umount",
      path: "/caked.Service/Umount",
      type: GRPCCallType.unary
    )
  }
}
