#!/bin/sh

set -e

echo "/Applications/Caker.app/Contents/MacOS" >> /etc/paths.d/com.aldunelabs.caker.public

# Create sudoers file for Caker
cat <<EOF > /etc/sudoers.d/caker
# Caker sudoers file
%everyone ALL=(root:wheel) NOPASSWD: /Applications/Caker.app/Contents/MacOS/caked
EOF

chgroup staff /etc/sudoers.d/caker

chmod 0664 /etc/sudoers.d/caker

# Install the Caker service
/Applications/Caker.app/Contents/MacOS/caked service install --system
