import ArgumentParser
import CakedLib
import CakeAgentLib
import Dispatch
import GRPC
import GRPCLib
import SwiftUI
import TextTable
import Virtualization

struct Networks: ParsableCommand {
	public struct VMNetOptions: ParsableArguments {
		@Flag(help: .private)
		public var debug: Bool = false

		@Argument(help: ArgumentHelp(String(localized: "socket path")))
		public var socketPath: String? = nil

		@Option(name: [.customLong("fd")], help: ArgumentHelp(String(localized: "Use file descriptor for VMNet")))
		public var vmfd: Int? = nil

		@Option(name: [.customLong("socket-group")], help: ArgumentHelp(String(localized: "socket group name")))
		public var socketGroup: String = "staff"

		@Option(name: [.customLong("mode")], help: ArgumentHelp(String(localized: "vmnet mode")))
		public var mode = VMNetMode.bridged

		@Option(name: [.customLong("interface")], help: ArgumentHelp(String(localized: "interface") + "\n", discussion: String(localized: "interface used for --vmnet=bridged, e.g., \"en0\"")))
		public var networkName: String = String.empty

		@Option(name: [.customLong("mac-address")], help: ArgumentHelp(String(localized: "Mac Address of network interface") + "\n", discussion: String(localized: "Mac address configured for VM network interface, autogenerated if not specified"), valueName: "mac"))
		public var macAddress: String = VZMACAddress.randomLocallyAdministered().string

		@Option(name: [.customLong("gateway")], help: ArgumentHelp(String(localized: "IP gateway") + "\n", discussion: String(localized: "gateway used for --vmnet=(host|shared), e.g., \"192.168.105.1\" (default: decided by macOS)")))
		public var gateway: String? = nil

		@Option(name: [.customLong("dhcp-end")], help: ArgumentHelp(String(localized: "end of the DHCP range") + "\n"))
		public var dhcpEnd: String? = nil

		@Option(help: ArgumentHelp(String(localized: "DHCP lease time in seconds")))
		public var dhcpLease: Int32? = nil

		@Option(name: [.customLong("netmask")], help: ArgumentHelp(String(localized: "Subnet mask") + "\n", discussion: String(localized: "requires --gateway to be specified")))
		public var subnetMask = "255.255.255.0"

		@Option(name: [.customLong("interface-id")], help: ArgumentHelp(String(localized: "VMNET interface ID") + "\n", discussion: String(localized: "randomly generated if not specified")))
		public var interfaceID = UUID().uuidString

		@Option(name: [.customLong("nat66-prefix")], help: ArgumentHelp(String(localized: "The IPv6 prefix to use with shared mode")))
		public var nat66Prefix: String? = nil

		@Option(name: [.customLong("pidfile")], help: ArgumentHelp(String(localized: "save pid to PIDFILE")))
		public var pidFile: String? = nil

		public init() {

		}

		public init(networkName: String, runMode: Utils.RunMode) throws {
			self.networkName = networkName

			self.debug = false
			self.networkName = networkName
			self.socketGroup = "staff"
			self.socketPath = nil
			self.vmfd = nil
			self.pidFile = nil

			if CakedLib.NetworksHandler.isPhysicalInterface(name: networkName) {
				self.mode = .bridged
				self.macAddress = VZMACAddress.randomLocallyAdministered().string
				self.gateway = nil
				self.dhcpEnd = nil
				self.dhcpLease = nil
				self.subnetMask = "255.255.255.0"
				self.interfaceID = UUID().uuidString
				self.nat66Prefix = nil
			} else {
				let home: Home = try Home(runMode: runMode)
				let networkConfig = try home.sharedNetworks()

				guard let network = networkConfig.sharedNetworks[networkName] else {
					throw ServiceError(String(localized: "Network \(networkName) doesn't exists"))
				}
				guard network.mode != .nat else {
					throw ServiceError(String(localized: "Network \(networkName) is default nated, please use a different network"))
				}

				if #available(macOS 26.0, *) {
					throw ServiceError(String(localized: "Network \(networkName) is handled natively, please use a different network"))
				}

				self.mode = network.mode
				self.gateway = network.dhcpStart
				self.dhcpEnd = network.dhcpEnd
				self.dhcpLease = network.dhcpLease
				self.subnetMask = network.netmask
				self.interfaceID = network.interfaceID
				self.nat66Prefix = network.nat66Prefix
			}
		}

		func validate() throws {
			if self.vmfd != nil && self.socketPath != nil {
				throw ValidationError(String(localized: "fd and socket-path are mutually exclusive \(self.vmfd!) \(self.socketPath!)"))
			}

			if let vmfd = self.vmfd {
				if self.pidFile == nil {
					throw ValidationError(String(localized: "pidfile is required when using fd"))
				}

				guard fcntl(Int32(vmfd), F_GETFD) != -1 || errno != EBADF else {
					throw ValidationError(String(localized: "File descriptor is not open"))
				}
			}

			if self.mode == .bridged {
				if self.networkName == String.empty {
					throw ValidationError(String(localized: "interface is required for bridged mode"))
				}

				if self.gateway != nil {
					throw ValidationError(String(localized: "gateway is not allowed for bridged mode"))
				}

				if self.dhcpEnd != nil {
					throw ValidationError(String(localized: "dhcp-end is not allowed for bridged mode"))
				}
			} else if let gateway = self.gateway {
				guard let gatewayAddr = IP.V4(gateway) else {
					throw ValidationError(String(localized: "gateway is not a valid IP address"))
				}

				guard let dhcpEnd = self.dhcpEnd else {
					throw ValidationError(String(localized: "dhcp-end is required for host/shared mode when gateway is specified"))
				}

				guard let dhcpEndAddr = IP.V4(dhcpEnd) else {
					throw ValidationError(String(localized: "dhcp-end is not a valid IP address"))
				}

				guard self.subnetMask.isValidNetmask() else {
					throw ValidationError(String(localized: "valid netmask is required for host/shared mode when gateway is specified"))
				}

				let cidr = self.subnetMask.netmaskToCidr()
				let network = IP.Block<IP.V4>(base: gatewayAddr, bits: UInt8(cidr)).network

				if network.contains(dhcpEndAddr) == false {
					throw ValidationError(String(localized: "dhcp-end is not in the same network as gateway"))
				}
			}
		}

		func vmnetEndpoint(runMode: Utils.RunMode) throws -> (socket: URL, pidFile: URL) {
			if let socketPath = self.socketPath, let pidFile = self.pidFile {
				return (URL(fileURLWithPath: socketPath), URL(fileURLWithPath: pidFile))
			} else {
				return try CakedLib.NetworksHandler.vmnetEndpoint(networkName: self.networkName, runMode: runMode)
			}
		}

		func createVZVMNet(runMode: Utils.RunMode) throws -> (URL, VZVMNet) {
			let network: VZSharedNetwork

			if CakedLib.NetworksHandler.isPhysicalInterface(name: self.networkName) {
				network = VZSharedNetwork(mode: self.mode, netmask: String.empty, dhcpStart: String.empty, dhcpEnd: String.empty, dhcpLease: nil, interfaceID: self.interfaceID, nat66Prefix: nil)
			} else {
				network = VZSharedNetwork(mode: self.mode, netmask: self.subnetMask, dhcpStart: self.gateway!, dhcpEnd: self.dhcpEnd!, dhcpLease: self.dhcpLease, interfaceID: self.interfaceID, nat66Prefix: self.nat66Prefix)
			}

			guard let vmfd = self.vmfd else {
				let socketURL = try vmnetEndpoint(runMode: runMode)

				guard let grp = getgrnam(self.socketGroup) else {
					throw ServiceError(String(localized: "Failed to get group \(self.socketGroup)"))
				}

				if let dhcpLease = self.dhcpLease {
					_ = try CakedLib.NetworksHandler.setDHCPLease(leaseTime: dhcpLease, runMode: runMode)
				}

				if try socketURL.socket.exists() == false {
					let vzvmnet = VZVMNetSocket(
						on: Utilities.group.next(),
						socketPath: socketURL.socket,
						socketGroup: grp.pointee.gr_gid,
						networkName: self.networkName,
						networkConfig: network,
						pidFile: socketURL.pidFile
					)

					return (socketURL.pidFile, vzvmnet)
				} else {
					throw ServiceError(String(localized: "Socket file already exists at \(socketURL.socket.path)"))
				}
			}

			guard let pidFile = self.pidFile else {
				throw ServiceError(String(localized: "pidfile is required when using vmfd"))
			}

			let pidUrl = URL(fileURLWithPath: pidFile)

			try? pidUrl.delete()

			let vzvmnet = VZVMNetFileHandle(
				on: Utilities.group.next(),
				inputOutput: CInt(vmfd),
				networkName: self.networkName,
				networkConfig: network,
				pidFile: pidUrl)

			return (pidUrl, vzvmnet)
		}
	}

	static let configuration: CommandConfiguration = CommandConfiguration(
		abstract: String(localized: "Manage host network devices"),
		subcommands: [
			Networks.NatInfos.self,
			Networks.Infos.self,
			Networks.List.self,
			Networks.Create.self,
			Networks.Configure.self,
			Networks.DHCPLease.self,
			Networks.Delete.self,
			Networks.Run.self,
			Networks.Start.self,
			Networks.Restart.self,
			Networks.Stop.self,
		],
		aliases: ["net"])

	static func validateNetwork(networkName: String, runMode: Utils.RunMode) throws {
		// Validate the network name
		if CakedLib.NetworksHandler.isPhysicalInterface(name: networkName) == false {
			let home: Home = try Home(runMode: runMode)
			let networkConfig = try home.sharedNetworks()

			if networkConfig.sharedNetworks[networkName] == nil {
				throw ValidationError(String(localized: "Network \(networkName) does not exist"))
			}
		}
	}

	static func start(options: Networks.VMNetOptions, runMode: Utils.RunMode) -> StartedNetworkReply {
		do {
			let socketURL = try options.vmnetEndpoint(runMode: runMode)

			if socketURL.pidFile.isCakedRunning() {
				return StartedNetworkReply(name: options.networkName, started: false, reason: String(localized: "Network already running"))
			}

			if geteuid() == 0 {
				try socketURL.pidFile.deleteIfFileExists()
				try socketURL.socket.deleteIfFileExists()

				let vzvmnet = try options.createVZVMNet(runMode: runMode)
				var signalReconfigure: DispatchSourceSignal? = nil

				if CakedLib.NetworksHandler.isPhysicalInterface(name: options.networkName) == false {
					let sig = DispatchSource.makeSignalSource(signal: SIGUSR2)

					if let dhcpLease = options.dhcpLease {
						_ = try CakedLib.NetworksHandler.setDHCPLease(leaseTime: dhcpLease, runMode: runMode)
					}

					Logger(self).info("Allow reconfigure network: \(options.networkName)")

					signal(SIGUSR2, SIG_IGN)

					sig.setEventHandler {
						Logger(self).info("Will reconfigure network: \(options.networkName)")

						do {
							let home: Home = try Home(runMode: runMode)
							let networkConfig = try home.sharedNetworks()

							if let network = networkConfig.sharedNetworks[options.networkName] {
								try? vzvmnet.1.reconfigure(networkConfig: network)
							}
						} catch {
							Logger(self).error("Failed to reconfigure network: \(error)")
							Foundation.exit(1)
						}
					}

					sig.activate()
					signalReconfigure = sig
				}

				defer {
					if let sig = signalReconfigure {
						sig.cancel()
					}
				}

				try vzvmnet.1.start()

				return StartedNetworkReply(name: options.networkName, started: true, reason: String(localized: "Network \(options.networkName) started"))
			} else if try SudoCaked(arguments: ["networks", "start", options.networkName], runMode: runMode, log: try CakedLib.NetworksHandler.vmnetFileLog(networkName: options.networkName, runMode: runMode)).run().terminationStatus != 0 {
				throw ServiceError(String(localized: "Failed to start networks \(options.networkName)"))
			} else {
				sleep(1)
				try socketURL.pidFile.waitPID()

				return StartedNetworkReply(name: options.networkName, started: true, reason: String(localized: "Network \(options.networkName) started"))
			}
		} catch {
			return StartedNetworkReply(name: options.networkName, started: false, reason: error.reason)
		}
	}

	struct NatInfos: ParsableCommand {
		static let configuration = CommandConfiguration(commandName: "nat-infos",
														abstract: String(localized: "default nat network address"),
														discussion: String(localized: "This command is used retrieve the default nat network address"),
														shouldDisplay: false)

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		func validate() throws {
			Logger.setLevel(self.common.logLevel)

			if #unavailable(macOS 26) {
				if geteuid() != 0 {
					throw ValidationError(String(localized: "This command must be run as root not as user \(geteuid())"))
				}
			}
		}

		func run() throws {
			Logger.appendNewLine(self.common.format.render(try CakedLib.NetworksHandler.natNetworkInfos()))
		}
	}

	struct Infos: ParsableCommand {
		static let configuration = NetworkInfoOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@Argument(help: ArgumentHelp(String(localized: "Network name"), discussion: String(localized: "The name for network")))
		var name: String

		func validate() throws {
			Logger.setLevel(self.common.logLevel)

			try validateNetwork(networkName: self.name, runMode: self.common.runMode)
		}

		func run() throws {
			let result = CakedLib.NetworksHandler.status(networkName: self.name, runMode: self.common.runMode)

			if result.success {
				Logger.appendNewLine(self.common.format.render(result.info))
			} else {
				Logger.appendNewLine(self.common.format.render(result.reason))
			}
		}
	}

	struct DHCPLease: ParsableCommand {
		static let configuration = CommandConfiguration(commandName: "set-dhcp-lease", abstract: String(localized: "Set DHCP lease duration."), discussion: String(localized: "This command is used to set the dhcp lease"))

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@Argument(help: ArgumentHelp(String(localized: "DHCP lease time in seconds")))
		var dhcpLease: Int32 = 300

		func validate() throws {
			Logger.setLevel(self.common.logLevel)
		}

		func run() throws {
			Logger.appendNewLine(self.common.format.render(try CakedLib.NetworksHandler.setDHCPLease(leaseTime: self.dhcpLease, runMode: self.common.runMode)))
		}
	}

	struct Start: ParsableCommand {
		static let configuration = NetworkStartOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@Argument(help: ArgumentHelp(String(localized: "Network name"), discussion: String(localized: "The name for network")))
		var name: String

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)

			try validateNetwork(networkName: self.name, runMode: self.common.runMode)

			let socketURL = try CakedLib.NetworksHandler.vmnetEndpoint(networkName: name, runMode: self.common.runMode)

			if socketURL.pidFile.isCakedRunning() {
				if let pid = socketURL.pidFile.readPID() {
					throw ValidationError(String(localized: "Network \(self.name) is already running with PID=\(pid)"))
				} else {
					throw ValidationError(String(localized: "Network \(self.name) is already running with undetermined PID"))
				}
			}

			//if FileManager.default.fileExists(atPath: socketURL.socket.path) {
			//	throw ValidationError(String(localized: "Listen network \(self.name) already exists at this location: \(socketURL.socket.path)"))
			//}
		}

		func run() throws {
			Logger.appendNewLine(self.common.format.render(Networks.start(options: try Networks.VMNetOptions(networkName: self.name, runMode: self.common.runMode), runMode: self.common.runMode)))
		}
	}

	struct Restart: ParsableCommand {
		static let configuration = CommandConfiguration(abstract: String(localized: "Restart named network."), discussion: String(localized: "This command is used to restart the VMNet network device."))

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@Argument(help: ArgumentHelp(String(localized: "Network name"), discussion: String(localized: "The name for network")))
		var name: String

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)

			try validateNetwork(networkName: self.name, runMode: self.common.runMode)

			let socketURL = try CakedLib.NetworksHandler.vmnetEndpoint(networkName: name, runMode: self.common.runMode)

			if FileManager.default.fileExists(atPath: socketURL.socket.path) == false {
				throw ValidationError(String(localized: "Network \(self.name) is not running"))
			}
		}

		func run() throws {
			Logger.appendNewLine(self.common.format.render(try CakedLib.NetworksHandler.restartNetworkService(networkName: self.name, runMode: self.common.runMode)))
		}
	}

	struct Create: AsyncParsableCommand {
		static let configuration = NetworkCreateOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@OptionGroup(title: String(localized: "Create networks options"))
		var options: NetworkCreateOptions

		var createdNetwork: VZSharedNetwork? = nil

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)

			let home: Home = try Home(runMode: self.common.runMode)
			let networkConfig = try home.sharedNetworks()

			if networkConfig.sharedNetworks[self.options.name] != nil {
				throw ValidationError(String(localized: "Network \(self.options.name) already exist"))
			}

			if CakedLib.NetworksHandler.isPhysicalInterface(name: self.options.name) {
				throw ValidationError(String(localized: "Network \(self.options.name) is a physical interface"))
			}

			let network = VZSharedNetwork(
				mode: self.options.mode == .shared ? .shared : .host,
				netmask: self.options.subnetMask,
				dhcpStart: self.options.gateway,
				dhcpEnd: self.options.dhcpEnd,
				dhcpLease: self.options.dhcpLease,
				interfaceID: self.options.interfaceID,
				nat66Prefix: self.options.nat66Prefix
			)

			try network.validate(runMode: common.runMode)
			self.createdNetwork = network
		}

		func run() async throws {
			Logger.appendNewLine(self.common.format.render(CakedLib.NetworksHandler.create(networkName: self.options.name, network: self.createdNetwork!, runMode: self.common.runMode)))
		}
	}

	struct Configure: ParsableCommand {
		static let configuration = NetworkConfigureOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@OptionGroup(title: String(localized: "Configure networks options"))
		var options: NetworkConfigureOptions

		var changedNetwork: VZSharedNetwork? = nil

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)

			let home: Home = try Home(runMode: self.common.runMode)
			let networkConfig = try home.sharedNetworks()

			if CakedLib.NetworksHandler.isPhysicalInterface(name: self.options.name) {
				throw ValidationError(String(localized: "Unable to configure physical network \(self.options.name)"))
			}

			guard let existing = networkConfig.sharedNetworks[self.options.name] else {
				throw ValidationError(String(localized: "Network \(self.options.name) does not exist"))
			}

			let changed = VZSharedNetwork(
				mode: existing.mode,
				netmask: self.options.subnetMask ?? existing.netmask,
				dhcpStart: self.options.gateway ?? existing.dhcpStart,
				dhcpEnd: self.options.dhcpEnd ?? existing.dhcpEnd,
				dhcpLease: self.options.dhcpLease ?? existing.dhcpLease,
				interfaceID: self.options.interfaceID ?? existing.interfaceID,
				nat66Prefix: self.options.nat66Prefix ?? existing.nat66Prefix
			)

			if existing != changed {
				try changed.validate(runMode: common.runMode)
			}

			self.changedNetwork = changed
		}

		func run() throws {
			Logger.appendNewLine(self.common.format.render(CakedLib.NetworksHandler.configure(networkName: self.options.name, network: self.changedNetwork!, runMode: self.common.runMode)))
		}
	}

	struct Delete: ParsableCommand {
		static let configuration = NetworkDeleteOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@Argument(help: ArgumentHelp(String(localized: "network name"), discussion: String(localized: "network to delete, e.g. \"shared\"")))
		var name: String

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)

			let home: Home = try Home(runMode: self.common.runMode)
			let networkConfig = try home.sharedNetworks()
			let socketURL = try CakedLib.NetworksHandler.vmnetEndpoint(networkName: self.name, runMode: self.common.runMode)

			if FileManager.default.fileExists(atPath: socketURL.socket.path) {
				throw ValidationError(String(localized: "Unable to delete running network \(self.name)"))
			}

			if CakedLib.NetworksHandler.isPhysicalInterface(name: self.name) {
				throw ValidationError(String(localized: "Unable to delete physical network \(self.name)"))
			}

			if networkConfig.sharedNetworks[self.name] == nil {
				throw ValidationError(String(localized: "Network \(self.name) does not exist"))
			}
		}

		func run() throws {
			Logger.appendNewLine(self.common.format.render(CakedLib.NetworksHandler.delete(networkName: self.name, runMode: self.common.runMode)))
		}
	}

	struct Run: AsyncParsableCommand {
		static let configuration = CommandConfiguration(abstract: String(localized: "Run internal VMNet network device"), shouldDisplay: false)

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@OptionGroup(title: String(localized: "Configure VMNet options"))
		var options: Networks.VMNetOptions

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)

			let socketURL = try self.options.vmnetEndpoint(runMode: self.common.runMode)

			if FileManager.default.fileExists(atPath: socketURL.socket.path) {
				throw ValidationError(String(localized: "Network already running"))
			}

			if geteuid() != 0 {
				throw ValidationError(String(localized: "This command must be run as root not as user \(geteuid())"))
			}

			if FileManager.default.fileExists(atPath: socketURL.socket.path) {
				throw ValidationError(String(localized: "Network already running"))
			}

			try self.options.validate()
		}

		func run() async throws {
			Logger.appendNewLine(self.common.format.render(Networks.start(options: self.options, runMode: self.common.runMode)))
		}
	}

	struct Stop: ParsableCommand {
		static let configuration = NetworkStopOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		@Argument(help: ArgumentHelp(String(localized: "network name"), discussion: String(localized: "network to stop, e.g., \"en0\" or \"shared\"")))
		var networkName: String? = nil

		@Option(name: [.customLong("pidfile")], help: .hidden)
		var pidFile: String? = nil

		func validate() throws {
			Logger.setLevel(self.common.logLevel)

			if networkName != nil && pidFile != nil {
				throw ValidationError(String(localized: "You can only specify one of --network or --pidfile"))
			}

			if networkName == nil && pidFile == nil {
				throw ValidationError(String(localized: "You must specify one of --network or --pidfile"))
			}

			if let networkName {
				try Networks.validateNetwork(networkName: networkName, runMode: self.common.runMode)
			} else if let pidFile {
				if !FileManager.default.fileExists(atPath: pidFile) {
					throw ValidationError(String(localized: "PID file \(pidFile) does not exist"))
				}
			}
		}

		func run() throws {
			if let pidFile {
				Logger.appendNewLine(self.common.format.render(CakedLib.NetworksHandler.stop(pidURL: URL(fileURLWithPath: pidFile), runMode: self.common.runMode)))
			} else if let networkName {
				Logger.appendNewLine(self.common.format.render(CakedLib.NetworksHandler.stop(networkName: networkName, runMode: self.common.runMode)))
			} else {
				throw ValidationError(String(localized: "No network name provided"))
			}
		}
	}

	struct List: ParsableCommand {
		static let configuration = NetworkListOptions.configuration

		@OptionGroup(title: String(localized: "Global options"))
		var common: CommonOptions

		mutating func validate() throws {
			Logger.setLevel(self.common.logLevel)
		}

		func run() throws {
			let result = CakedLib.NetworksHandler.networks(runMode: self.common.runMode)

			if result.success {
				Logger.appendNewLine(self.common.format.render(result.networks))
			} else {
				Logger.appendNewLine(self.common.format.render(result.reason))
			}
		}
	}
}
